### ISSUE TITLE
Doc: Version history of l-filesToScp not complete

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#112]
https://github.com/UnifiedViews/Plugins/blob/master/l-filesToScp/README.md contains info about version 1.3.1 no additional versions mentioned, but latest version is 1.5.0 (https://github.com/UnifiedViews/Plugins/blob/master/l-filesToScp)

**Comment by mkl-eea-sk** [comment]
This DPU is obsolete, does it make sense to update docs?

**Comment by skrchnavy** [comment]
Yes, there shell be also comments about new DPU that shall be used.
