### ISSUE TITLE
Doc: Version history of l-filesToLocalFS not complete

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#113]
https://github.com/UnifiedViews/Plugins/blob/master/l-filesToLocalFS/README.md contains info about version 1.3.1 no additional versions mentioned, but latest version is 1.6.0 (https://github.com/UnifiedViews/Plugins/blob/master/l-filesToLocalFS)

**Comment by mkl-eea-sk** [comment]
This DPU is obsolete, does it make sense to update docs?
