### ISSUE TITLE
e-filesDownload configuration/features aligned with e-httpDownload

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#120]
It is related to #93.
To update also https://github.com/UnifiedViews/Plugins/tree/develop/e-filesDownload DPU to be compatible with e-httpDownload as much as possible. (for example to support download of files that are sent on optional input data unit.

**Comment by skrchnavy** [comment]
@tomas-knap are these DPUs compatible from configuration point of view? Are we able to replace one with the other?
I mean manual reconfiguration, if all parameters that were configurable in e-httpDownload are possible to setup in filesDownload.

And additional question ( @skodape could help): is there a possibility to define migration of configuration from e-httpDownload to e-filesDownload?

**Comment by skodape** [comment]
e-FilesDownload can be use configuration of following DPUs:
* eu.unifiedviews.plugins.uv-e-filesFromLocal https://github.com/UnifiedViews/Plugins/blob/develop/e-filesDownload/src/main/java/cz/cuni/mff/xrg/uv/extractor/filesfromlocal/FilesFromLocalConfig_V1.java
* cz.cuni.mff.xrg.uv.e-HttpDownload https://github.com/UnifiedViews/Plugins/blob/develop/e-filesDownload/src/main/java/cz/cuni/mff/xrg/uv/extractor/httpdownload/HttpDownloadConfig_V2.java
* cz.cuni.mff.xrg.uv.e-filesFromScp https://github.com/UnifiedViews/Plugins/blob/develop/e-filesDownload/src/main/java/cz/cuni/mff/xrg/uv/extractor/scp/FilesFromScpConfig_V1.java
* eu.unifiedviews.plugins.uv-e-httpDownload https://github.com/UnifiedViews/Plugins/blob/develop/e-filesDownload/src/main/java/eu/unifiedviews/plugins/extractor/httpdownload/HttpDownloadConfig_V1.java

If you are interest in a way how the conversion is done, please refer to respective  source code (method toNextVersion).

**Comment by tomas-knap** [comment]
Configuration from the previous DPUs is compatible.
