### ISSUE TITLE
new DPU: find and replace in files

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#121]
DPU is requested to be able to cleanup files using search and replace approach to correct errors in files.
(similar to functionality in text editors).
Some high level requirements:
* multiple replace patterns to be defined
* support for multiple files on the input
* string to string replacement
* case sensitive/insensitive support
* support for basic escape characters (\n, \r, \l, \t, ...)
* configuration dialog not too complex.

inspiration could be https://findandreplace.codeplex.com/ but not strictly required.

**Comment by mkl-eea-sk** [comment]
| multiple replace patterns to be defined
todo - change config dialog only
| support for multiple files on the input
DONE
| string to string replacement
DONE
| case sensitive/insensitive support
TODO - change dialog, change config class, change engine
| support for basic escape characters (\n, \r, \l, \t, ...)
DONE - support java string literal notation
| configuration dialog not too complex.
DONE

**Comment by skrchnavy** [comment]
>> support for multiple files on the input
> DONE
Also dialog is finalized for this support?

**Comment by skrchnavy** [comment]
To correct Readme.md to reflect this DPU. Also resources uses not proper keys.

**Comment by mkl-eea-sk** [comment]
readme is fine, which resources use not proper keys?

**Comment by skrchnavy** [comment]
at this commit: 9a493b6416cd7df056fa455d0da0b1a843ed9aea t-filesFindAndReplace/README.md:
- Name:	L-FilesFindAndReplace

**Comment by mkl-eea-sk** [comment]
extended comments

**Comment by skrchnavy** [comment]
#174 pull request closed, can we close also this? Any outstanding issues?

**Comment by skrchnavy** [comment]
#174 closed, so cl0sing
