### ISSUE TITLE
T-RdfToFiles - RDF format could be "Auto" options in dialog

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Plugins#122]
![bug](https://cloud.githubusercontent.com/assets/5822680/6243918/01c92364-b74c-11e4-9da7-fdf01dbdc56c.png)

so that a user doesn't have to set this parameter explicitly.

**Comment by hanecak** [comment]
"Auto" would mean user will not know what the format will actually be. He will be forced to either look into some user documentation or do a "blind test" (running a pipe line and looking what it did). That's bad.

Simple select one from the values as sensible default. Given http://www.w3.org/TR/rdf11-new/#section-serializations (and ignoring current UV capabilities) I would choose Turtle or TriG. I leave final decision to @tomas-knap .

**Comment by Jan-Marcek** [comment]
However,
openRDF provides "Auto" functionality itself http://rdf4j.org/sesame/2.7/apidocs/org/openrdf/rio/RDFFormat.html#forFileName%28java.lang.String%29.

**Comment by jakubklimek** [comment]
That is mainly for reading files - when you are reading RDF files that have extensions, it is possible to determine the probable RDF format from the extension.

This does not make sense for writing RDF files - here I need to choose the RDF format to use.

I suggest to close this issue as won't fix.

**Comment by skrchnavy** [comment]
Wouldn't be an option to set default (instead of Auto)? I see one scenarion where it hase sence, pipeline transforms data and some intermediate format is file with triples that will be processed in next DPUs and then later uploaded into some storage or another form. So it is not important to know the format.
Probably same as @jindrichmynarz comment.

Disadvantage is that user is not forced to set proper format, but if user doesn't know the format needed in another DPUs then this DPU is not for such user.

**Comment by tomas-knap** [comment]
Yes, the auto option is based on the file extension. So it basically looks into the extension, and selects the format - this option typically works and is the most generic and useful. So it is valid requirement.

**Comment by tomas-knap** [comment]
In the case of this DPU, the output format is needed to know how the RDF data should be serialized. So in this case, AUTO option does not make much sense. 

Solution: Set Turtle as defaut option.

**Comment by mkl-eea-sk** [comment]
@mbl-eea-sk check by looking into code whether Turtle is the default (in *Config_V1 class). If it is, this issue is resolved. If not, set it to Turtle and make pull request.

**Comment by mbl-eea-sk** [comment]
The dafault value is set to Turtle.
https://github.com/UnifiedViews/Plugins/blob/master/t-rdfToFiles/src/main/java/eu/unifiedviews/plugins/transformer/rdftofiles/RdfToFilesConfig_V1.java#L53

**Comment by skrchnavy** [comment]
Issue is invalid, Auto is not requested, Turtle is default. Closing.
