### ISSUE TITLE
E-FilesFromLocal: incorrect line break in the configuration dialog

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#123]
Using E-FilesFromLocal from the develop branch (commit 63f6fb4cb7206040fca328c97c235340b3cafa99), its configuration dialog displays `</br>` (NB: `br` element doesn't have a closing tag) instead of an actual line break.

![screen shot 2015-02-19 at 13 17 02](https://cloud.githubusercontent.com/assets/198642/6266413/c4aeb2d4-b839-11e4-95b1-76656b935b6f.png)

**Comment by skrchnavy** [comment]
@jindrichmynarz is this valid for replaced DPU (e-filesDownload)

**Comment by jindrichmynarz** [comment]
No, it is not valid for e-filesDownload. Closing this issue.
