### ISSUE TITLE
L-filesToLocalFS: pipeline validation reports missing input/output

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#124]
Using the L-filesToLocalFS from the develop branch (commit 63f6fb4cb7206040fca328c97c235340b3cafa99) in loaded UnifiedViews from the develop branch ([commit](https://github.com/UnifiedViews/Core/commit/4ed9b6172c3547924753de3e45621cce7332c327)) pipeline validation throws this error:

![screen shot 2015-02-19 at 14 28 58](https://cloud.githubusercontent.com/assets/198642/6267382/bceccdf6-b843-11e4-9186-b96834311ca2.png)

The `filesInput` parameter of L-filesToLocalFS is mapped to the `output` parameter of E-FilesFromLocal:

![screen shot 2015-02-19 at 14 31 08](https://cloud.githubusercontent.com/assets/198642/6267408/f6f60210-b843-11e4-9afa-8c2a5b547074.png)

L-filesToLocalFS doesn't offer an option to set it's fileInput parameter via its dialog:
![screen shot 2015-02-19 at 14 31 40](https://cloud.githubusercontent.com/assets/198642/6267427/2cd4c3ee-b844-11e4-90e4-536e5034739a.png)

This is either a bug of L-filesToLocalFS GUI or of the validation in Core (if that's the case, we move this issue there).

**Comment by mkl-eea-sk** [comment]
obsolete dpu?

**Comment by jindrichmynarz** [comment]
Yes. Closing the issue.
