### ISSUE TITLE
uv-e-filesDownload - duplicity rows

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Plugins#125]
When I import uv-e-filesDownload and open configuration there is one line. When I click save, there are two lines, if I click save again there are four.. etc .. 

If I switch to another DPU and back, there is only one line - that's right. The table is probably not cleared before new data are loaded.

**Comment by eea01** [comment]
Test environment edem.eea.sk.
Core, develop branch, [latest revision](https://github.com/UnifiedViews/Core/commit/860580b74332b0656dca48cb26a89beb875b6289).
e-filesDownload, develop branch, [latest revision](https://github.com/UnifiedViews/Plugins/commit/f09fda4b021b1d09e9cca5f7e94fcfdffbe79d0c).
Browser Internet Explorer, Firefox.

I was not able to reproduce described behavior.
