### ISSUE TITLE
All DPUs that allow to specify character encoding should provide a select list

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#129]
All DPUs that allow to specify character encoding (such as t-tabular) should provide a select list of the supported character encodings rather than free-text input box. This would avoid the need of a user to figure out what codes of character encodings are supported by a DPU. For example, [Windows-1250](http://en.wikipedia.org/wiki/Windows-1250) encoding is commonly referred to as `cp1250` or `windows-1250`; however, by trial and error I found that t-tabular knows this encoding as `Cp1250`. Having a dropdown select box with a list of supported character encodings would avoid this issue.

**Comment by skrchnavy** [comment]
@jindrichmynarz do you have additional DPUs that have this issue?

**Comment by jindrichmynarz** [comment]
Besides t-tabular I know of:

* [UVPlugin-ISO2709ToMarcXML](https://github.com/OpenDataNode/UVPlugin-ISO2709ToMarcXML)
* [t-tabularToRelational](https://github.com/UnifiedViews/Plugins/tree/develop/t-tabularToRelational)

In [t-filesFindAndReplace](https://github.com/UnifiedViews/Plugins/tree/develop/t-filesFindAndReplace) there's already a select box for choosing character set, so we may want to harmonize what character sets are available by default.

**Comment by skrchnavy** [comment]
This issue will be closed when listed DPUs are updated.

**Comment by skrchnavy** [comment]
dependant issues solved, closing
