### ISSUE TITLE
SPARQL loader label wrong

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#13]
![image](https://cloud.githubusercontent.com/assets/718827/2859955/029f84b2-d1bb-11e3-8f33-6cab5014b80e.png)

there should be no "(file data unit)" because the output is RDF data unit.

**Comment by pedrinazzi** [comment]
Please , could you confirm the name of the DPU involved? Is it still available?

**Comment by tomas-knap** [comment]
Won't fix, this checkbox is not in the latest version of this DPU
