### ISSUE TITLE
New DPU t-tarql: tarql wrapper

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#130]
I propose to wrap [tarql](https://github.com/tarql/tarql) as a new DPU to transform tabular input into RDF output via SPARQL mapping. This has been [done before for a previous version of UnifiedViews](https://github.com/opendatacz/Tarql_extractor), so the new DPU can be inspired by this effort.

**Motivation:** Using [t-tabular](https://github.com/UnifiedViews/Plugins/tree/master/t-tabular) jointly with [t-sparql](https://github.com/UnifiedViews/Plugins/tree/master/t-sparql) for mapping tabular data to RDF is arduous and clunky. The fixed mapping in t-tabular is inflexible (e.g., handling identifiers) and introduces and arbitrary ontology (`http://linked.opendata.cz/ontology/odcs/tabular/`) and creates non-existing properties from the tabular input's header (n.b.: when the column name contains non-ASCII characters, they are stripped; e.g., "Názov EZÚS" => "Nzov-EZS"). Tarql, on the other hand, provides a more expressive (and, subjectively, easier to use) mapping of tabular data into RDF (e.g., the [original mapping for `CTIA_1`](https://github.com/opendatacz/COI2RDF/blob/master/kontroly/transformation.rq)).

**Comment by martinnec** [comment]
Does TARQL support large CSV? I remember we had a problem with this a year ago. If yeas, why not. Who has a capacity to do this?

Note : The idea of tabular was to do a "sstupid" transformation to some RDF and then to do everything necessary with sparql and other DPUs. TARQL allows to query a table with SPARQL, so you need the whole transformation logic in your SPARQL - what is the benefit?

**Comment by jindrichmynarz** [comment]
Processing large tables was an issue before, but since September 2014 (see [commit](https://github.com/tarql/tarql/commit/742ba8aa5bf00d2ac598c47d7455f17160c05f88)) tarql doesn't load the whole input into memory, but instead processes it as a stream.

Regarding the question about who has the capacity to do this, it would be great if some of the developers could provide an estimated time of implementation (possibly based on the [previously implemented tarql wrapper DPU](https://github.com/opendatacz/Tarql_extractor)).

As you pointed out, you're still limited to SPARQL with tarql when mapping tabular data to RDF. However, you work directly with the input data and not an oblique representation using `http://linked.opendata.cz/ontology/odcs/tabular/` vocabulary. In particular, when using tarql, you're free to decide how your URIs will be generated, whereas t-tabular relies on a column with natural key that is taken as is.

My point is that while everything that is possible with tarql can be done with t-tabular + t-sparql, using tarql is simpler as it directly works with the input data without the intermediate RDF representation (and, at least for me, easier). In my view the usability of tarql is better than when using t-tabular + t-sparql.

**Comment by martinnec** [comment]
If we find a capacity, why not.

**Comment by jindrichmynarz** [comment]
We can argue that spending some capacity on this DPU saves the capacity of pipeline creators.

**Comment by mkl-eea-sk** [comment]
If the Tarql produce Turtle file I would propose DPU which produce FileDataUnit and leave to pipeline designer if he wish to turn it to RDFDataUnit (filesToRdf).
