### ISSUE TITLE
T-Metadata uses U.S. date format by default

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#131]
Using the develop branch (commit bdfaf8791851119a186887a33142f0d261e53f0d) the date picker in the t-metadata DPU uses U.S. date format (i.e. `MM/DD/YYYY`) by default (e.g., `2/24/15`). I would except the date format to be determined by language content negotiation (e.g., `Accept-Language` HTTP header) or, given the excepted audience, the data format would be in "neutral" YYYY-MM-DD format.

**Comment by mkl-eea-sk** [comment]
obsolete dpu?

**Comment by jindrichmynarz** [comment]
Yes. I'm closing the issue.
