### ISSUE TITLE
T-Metadata: add button doesn't work

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#132]
Using the develop branch (commit bdfaf8791851119a186887a33142f0d261e53f0d) the add button (`+`) available for fields such as "Available licenses", "Available keywords" or "Available authors" in the T-Metadata DPU doesn't work. Tested in Google Chrome (version 40.0.2214.115), Mozilla Firefox (version 32.0.3) and Safari (version 7.1.3).

**Comment by skrchnavy** [comment]
@tomas-knap is this valid? T-Metadata shall be obsoleted

**Comment by tomas-knap** [comment]
Yes, this is obsolete, t-metadata is deprecated. Closing
