### ISSUE TITLE
e-filesDownload, HTTP, not working

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Plugins#135]
I hope I just miss test something .. I use e-fileDownload version 1.0.0 commit 
9f1f12d47e3d5d56c26169dfabac663b2da17d67 - https://github.com/UnifiedViews/Plugins/commit/9f1f12d47e3d5d56c26169dfabac663b2da17d67

Try to download:
http://www.ctu.cz/otevrena-data/katalog-otevrenych-dat-ctu.html?action=detail&data_id=21
http://www.ctu.cz/otevrena-data/katalog-otevrenych-dat-ctu.html?action=detail&data_id=23
as 21.html and 23.html.

In my case two two files on output are the same. This is a huge problem as we replaced all our HttpDownloaders with this DPU .... :(

**Comment by skrchnavy** [comment]
Not clear from the description. Those 2 links shall be placed to configuration of DPU, or another steps to reproduce?

**Comment by skodape** [comment]
Yes, put those two into configuration. One as item, shal I provide screen shoot?

**Comment by skrchnavy** [comment]
@eea01 please check

**Comment by mkl-eea-sk** [comment]
Commit link points to rdfToFiles

**Comment by skrchnavy** [comment]
Yes, but it is in develop branch, so it shall be reproducible.

**Comment by skodape** [comment]
@eea01 I know why the cache is set to NullFilesCache - this is the fix right.

But why do you add Resource in this commit as well?

**Comment by eea01** [comment]
Setting the NullFilesCache is the fix, that is correct.
Changes from line [78](https://github.com/UnifiedViews/Plugins/commit/ff7862ab5cbbd633e093ddee5fbdd99e2f2d1882#diff-21384e9264e18d813763c4260c86a27eL78) to [102](https://github.com/UnifiedViews/Plugins/commit/ff7862ab5cbbd633e093ddee5fbdd99e2f2d1882#diff-21384e9264e18d813763c4260c86a27eR102) are:
1. From `if (fileObjects == null) { continue; }` to `if (fileObjects != null) {`.
2. Indentation.

**Comment by skodape** [comment]
Great thank yout
