### ISSUE TITLE
t-filesFindAndReplace: Improvement  - case sensitive, multiple find/replace entries, support for big files

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#136]
As an extension of #121, these features shall be implemented:
* case sensitive/insensitive support
* multiple find/replace entries to be configured
* support for big files (due to implementation when whole file is loaded into memory this shall be considered).

**Comment by jindrichmynarz** [comment]
@mkl-eea-sk: Can you also update the [README](https://github.com/UnifiedViews/Plugins/blob/feature/dpu/t-filesFindAndReplace/t-filesFindAndReplace/README.md), which seems to be copied & pasted without change L-FilesToLocalFS.

**Comment by skrchnavy** [comment]
@jindrichmynarz I have requested @mkl-eea-sk  to do it i #121, this issue is to follow further extensions (not implemented features in #121).
