### ISSUE TITLE
e-filesDownload, HTTP, not working

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Plugins#137]
Steps to reproduce:
* Put a single DPU e-filesDownload (*) on a pipelinne.
* Download file "http://www.isvav.cz/h13/organizationVoDetail.do?rowId=VOL" (put this value into column for a URI, leave other columns blank).
* Execute pipeline, does not matter if in debug mode or not.

(*) 
* Version of develop: https://github.com/UnifiedViews/Plugins/commit/300c0a8854d32936f5da1172ab728b2f575057da
* Last commit to DPU: https://github.com/UnifiedViews/Plugins/commit/ff7862ab5cbbd633e093ddee5fbdd99e2f2d1882

Fail message I got: 
```
Execution failed because: Exception occured while downloading files.eu.unifiedviews.dpu.DPUException: Exception occured while downloading files.
at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownload.execute(FilesDownload.java:107)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not determine the type of file "http://www.isvav.cz/h13/organizationVoDetail.do?rowId=VOL".
at org.apache.commons.vfs2.provider.AbstractFileObject.getType(AbstractFileObject.java:505)
at org.apache.commons.vfs2.provider.AbstractFileObject.exists(AbstractFileObject.java:477)
at org.apache.commons.vfs2.provider.AbstractFileObject.findFiles(AbstractFileObject.java:1192)
at eu.unifiedviews.plugins.extractor.filesdownload.FilesDownload.execute(FilesDownload.java:79)
... 4 more
Caused by: org.apache.commons.vfs2.FileSystemException: HEAD method failed for "http://www.isvav.cz/h13/organizationVoDetail.do?rowId=VOL".
at org.apache.commons.vfs2.provider.http.HttpFileObject.doGetType(HttpFileObject.java:94)
at org.apache.commons.vfs2.provider.AbstractFileObject.getType(AbstractFileObject.java:496)
... 7 more
```

**Comment by mkl-eea-sk** [comment]
$ curl -v -X HEAD http://www.isvav.cz/h13/organizationVoDetail.do?rowId=VOL
* Hostname was NOT found in DNS cache
*   Trying 147.32.3.129...
* Connected to www.isvav.cz (147.32.3.129) port 80 (#0)
 > HEAD /h13/organizationVoDetail.do?rowId=VOL HTTP/1.1
 > User-Agent: curl/7.35.0
 > Host: www.isvav.cz
 > Accept: */*
 >
< HTTP/1.1 500 Internal Server Error
< Date: Fri, 06 Mar 2015 08:35:01 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 3090
< Connection: close
<
* transfer closed with 3090 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 3090 bytes remaining to read

server responds with HTTP 500. What is Apache VFS2 supposed to do?
According to
http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html
quote:
| The HEAD method is identical to GET except that the server MUST NOT 
return a message-body in the response. The metainformation contained in 
the HTTP headers in response to a HEAD request SHOULD be identical to 
the information sent in response to a GET request. This method can be 
used for obtaining metainformation about the entity implied by the 
request without transferring the entity-body itself. This method is 
often used for testing hypertext links for validity, accessibility, and 
recent modification

The server does not respect the RFC. Should we report to the maintaner 
of server?

How to overcome this issue, is questionable. Usually, we trust other 
systems to work according to specifications (RFC for example).
Tomas Knap: what do you think we should do?

**Comment by jakubklimek** [comment]
From my machine:

$  curl -v -X HEAD http://www.isvav.cz/h13/organizationVoDetail.do?rowId=VOL
* STATE: INIT => CONNECT handle 0x600056170; line 1034 (connection #-5000)
* Hostname was NOT found in DNS cache
*   Trying 147.32.3.129...
* STATE: CONNECT => WAITCONNECT handle 0x600056170; line 1087 (connection #0)
* Connected to www.isvav.cz (147.32.3.129) port 80 (#0)
* STATE: WAITCONNECT => DO handle 0x600056170; line 1233 (connection #0)
> HEAD /h13/organizationVoDetail.do?rowId=VOL HTTP/1.1
> User-Agent: curl/7.38.0
> Host: www.isvav.cz
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x600056170; line 1319 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x600056170; line 1445 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x600056170; line 1458 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 500 Internal Server Error
< Date: Fri, 06 Mar 2015 08:43:49 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 3090
< Connection: close
<
* transfer closed with 3090 bytes remaining to read
* Closing connection 0
* The cache now contains 0 members
* Expire cleared
curl: (18) transfer closed with 3090 bytes remaining to read

**Comment by mkl-eea-sk** [comment]
yup, even for jakub, it does not work.

**Comment by jakubklimek** [comment]
OK, why is it necessary to use HTTP HEAD? It is nice that according to RFC it should work, but in reality when it does not work, the DPU is useless - this case.
HTTP GET works in this instance.

**Comment by skodape** [comment]
Note: I tried older HTTP downloaders (Core, CUNI) and they works (see cuni-test1), pipeline 323.

**Comment by jakubklimek** [comment]
Yes, because they do not use HEAD. So the question is whether this is configurable or not

**Comment by tomas-knap** [comment]
Please check whether we can easily customize the VFS lib. If not, we cannot use it to get data for certain comsode pipelines and another DPU must be used.

**Comment by tomas-knap** [comment]
Any progress? Thanks.

**Comment by tomas-knap** [comment]
If we cannot remove the bug, CUNI basically has to further use the deprecated e-httpDownloader

**Comment by mkl-eea-sk** [comment]
This is my responsibility?

**Comment by eea01** [comment]
It is my responsibility. I will investigate the issue as soon as possible.

**Comment by tomas-knap** [comment]
Thanks, please look on that asap, best today, latest by Monday. Otherwise, such DPU cannot be used and e-httpDownloader has to be used, which is step back
