### ISSUE TITLE
e-filesDownload, strange encoding of URL

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#145]
Testing of e-filesDownload to extract data from SAŽP. URL used:

http://inspire.geop.sazp.sk/geoserver/wfs?request=GetFeature&version=1.1.0&outputFormat=gml32&typename=ps%3AProtectedSite&cql_filter=%22ps%3AsiteDesignation%2Fps%3ADesignationType%2Fps%3Adesignation%22%20in%20('naturalMonument')%20and%20%22ps%3AinspireID%2Fbase%3AIdentifier%2Fbase%3Anamespace%22%20%3D%20'SK%3AGOV%3AMOE%3ASEA%3APS'

Using curl with above url, it works.

Using e-filesDownload with above URL, following error message is raised:
```
Lexical error at line 1, column 1.  Encountered: "%" (37), after : "" Parsing :                                  %22ps%3AsiteDesignation%2Fps%3ADesignationType%2Fps%3Adesignation%22%20in%20('naturalMonument')%20and%20%22ps%3AinspireID%2Fbase%3AIdentifier%2Fbase%3Anamespace%22%20%3D%20'SK%3AGOV%3AMOE%3ASEA%3APS'
```

Probable root cause of the problem is a way how e-filesDownload process escapes in URL.

Is it possible to log URL that is requested from server? Strange is that the error message is the same as URL.

Note: v e-httpDownload works with the URL correctly

Solution: Test the mentioned URL and correct the bug.

**Comment by tomas-knap** [comment]
@jindrichmynarz Please test whether it solved your problem

**Comment by jindrichmynarz** [comment]
Works as expected. It seems that the DPU now handles even unescaped query parameters. Is that correct, @eea01?

**Comment by eea01** [comment]
DPU was supporting only human readable URI input (decoded), now it supports also encoded input.
