### ISSUE TITLE
t-filesRenamer cannot add file suffix

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#146]
When the input file of t-filesRenamer doesn't have any file suffix, the DPU cannot add it one. It can only change existing file suffix.

For instance, this happens when <http://inspire.geop.sazp.sk/geoserver/wfs?request=GetFeature&version=1.1.0&outputFormat=gml32&typename=ps%3AProtectedSite&cql_filter=%22ps%3AsiteDesignation%2Fps%3ADesignationType%2Fps%3Adesignation%22%20in%20(%27nationalPark%27%2C%20%27ProtectedLandscapeOrSeascape%27)%20and%20%22ps%3AinspireID%2Fbase%3AIdentifier%2Fbase%3Anamespace%22%20%3D%20%27SK%3AGOV%3AMOE%3ASEA%3APS%27> is downloaded via e-filesDownload and passed to t-filesRenamer.

**Comment by eea02** [comment]
Implementation of this DPU has changed completely, during upgrade to 2.0 version of DPU helpers. Previous functionality is gone, so I can no longer provide support to it. Can you please retest it, with new version?

**Comment by skrchnavy** [comment]
@skodape please check your changes comparing to the changes done in master branch.

**Comment by jindrichmynarz** [comment]
@eea02: It's true that the DPU changed completely and therefore this bug is no longer relevant.

However, it's still not clear to me, how to add a file suffix with this DPU. The example above produces a file on the path `geoserver/wfs`. It seems that neither `wfs`, nor `geoserver/wfs` or `geoserver\\/wfs` matches this path in the t-filesRename.

What can be fixed as well is the usability of the new DPU. For example, is Java regular expression syntax expected? Are any flags for matching assumed or should we expect the default to be case sensitive and replacing only the first match found (i.e. global flag is not used)?

**Comment by skrchnavy** [comment]
This is related to #49 - it was implemented to follow some rename possibilities of file renaming inspired by multi rename tool in total commander
In migration it was not expected to rework the behaviour, just adapt to new helpers.

**Comment by jindrichmynarz** [comment]
My comment also highlights the issue with documentation of the t-filesRenamer DPU. Even though the DPU's interface was completely reworked, its [README](https://github.com/UnifiedViews/Plugins/blob/develop/t-filesRenamer/README.md) wasn't updated.

**Comment by tomas-knap** [comment]
Adressed by https://github.com/UnifiedViews/Plugins/pull/163
