### ISSUE TITLE
filesDownloader, feature "cache"

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Plugins#157]
FilesDownloader missing feature "cache" that is presented in uk-e-httpDownloader.

This feature enables optional caching for downloaded files. This is useful when downloading 100+ files  during pipeline development, as pipeline can be executed several times in an hour. The problem might be with speed, disk usage and source over utilization.

This prevent us from using FilesDownloader as replacement for uk-e-httpDownloader.

**Comment by jindrichmynarz** [comment]
See also [this thread](https://groups.google.com/forum/#!topic/unifiedviews/xrm5zW0Gfb4) in the UnifiedViews mailing list.

**Comment by skrchnavy** [comment]
DPU is based on VFS, so this could be useful also: http://wiki.apache.org/commons/VfsCacheStrategy

**Comment by tomas-knap** [comment]
Problematic with multiple backends environment
