### ISSUE TITLE
t-sparqlUpdate - problem with the query

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#159]
1) Try to run pipeline 
https://cuni-test1.comsode.eea.sk/unifiedviews/#!PipelineEdit/236. 
2) Observe the error produced

There is t-sparqlUpdate used in the pipeline, with the query: 

###

PREFIX dcterms:  <http://purl.org/dc/terms/> 
PREFIX skos:     <http://www.w3.org/2004/02/skos/core#> 

INSERT {
  ?narrower skos:broader ?broader .
  ?broader skos:narrower ?narrower .
}
WHERE {
  ?narrower a skos:Concept ;
    skos:notation ?code .
  
  FILTER(STRLEN(?code) = 4)

  BIND ("http://linked.data.comsode.eu/resource/domain/slovak.statistics.sk/" AS ?namespace)
  BIND (CONCAT(?namespace, "taxonomy/international-classification-of-diseases/") AS ?baseUri)
  BIND (IRI(CONCAT(?baseUri, LCASE(REPLACE(?code, "^([0-Z]{3})\\d$", "$1")))) as ?narrower) 
}

###

According to http://sparql.org/update-validator.html, such query is valid. But when the pipeline is executed it fails with: 

Type: PIPELINE_ERROR
Short message: Pipeline execution failed.
Message:
Execution failed because: Operation failed.eu.unifiedviews.dpu.DPUException: Operation failed. at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.checkFailState(FaultTolerance.java:242) at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.execute(FaultTolerance.java:300) at cz.cuni.mff.xrg.uv.transformer.sparql.update.SparqlUpdate.updateEntries(SparqlUpdate.java:151) at cz.cuni.mff.xrg.uv.transformer.sparql.update.SparqlUpdate.innerExecute(SparqlUpdate.java:106) at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370) at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452) at java.lang.Thread.run(Thread.java:745) Caused by: eu.unifiedviews.dpu.DPUException: Problem with query. at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:205) at cz.cuni.mff.xrg.uv.transformer.sparql.update.SparqlUpdate.executeUpdateQuery(SparqlUpdate.java:197) at cz.cuni.mff.xrg.uv.transformer.sparql.update.SparqlUpdate$4.action(SparqlUpdate.java:156) at eu.unifiedviews.helpers.dpu.extension.faulttolerance.FaultTolerance.execute(FaultTolerance.java:297) ... 7 more

###

**Comment by tomas-knap** [comment]
@jindrichmynarz, trying to reproduce the bug by running pipeline 236, but it does not show any error. Was it already corrected? 

If not, please adjust the description.

**Comment by jindrichmynarz** [comment]
Neither I can replicate this previously encountered bug.
