### ISSUE TITLE
Test 4 relationalDPUs in UV/Plugins which were upgraded to helpers 2.0

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#165]
@skodape adjusted the DPUs, they are in the branches: 

dpu/L-RelationalToSql-0.9.1 
dpu/T-Relational-0.9.1-SNAPSHOT
dpu/E-RelationalFromSql-1.0.1
dpu/T-TabularToRelational-1.0.1-SNAPSHOT

So please allocate somebody who will test the upgraded helpers, so that they work as expected.

**Comment by skrchnavy** [comment]
@eea03 please test the conversion and report issues, then we will discuss further steps

**Comment by eea02** [comment]
I have tested these pipelines:
dpu/L-RelationalToSql-0.9.1
dpu/T-Relational-0.9.1-SNAPSHOT
dpu/T-TabularToRelational-1.0.1-SNAPSHOT
After small fix, they are working as intended.
