### ISSUE TITLE
Define pom.xml formatting

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Plugins#166]
@tomas-knap  
At least we should decide if tabs or spaces shall be used.

This can be very helpful as now there is (best to my knowledge) no rule nor recommendation in this area.

**Comment by skrchnavy** [comment]
@tomas-knap I expected this was defined in the eclipse formater. If I remember, with @skodape we somehow agreed that tabs shall be used.

**Comment by Jan-Marcek** [comment]
It is at : https://github.com/UnifiedViews/Core/tree/master/code_template 
I don't think we need more then one template.

**Comment by skrchnavy** [comment]
Is this valid also for xml files (including pom.xml)?

**Comment by tomas-knap** [comment]
The problem is that template is not automatically applied to xml files.

Solution: Use spaces everywhere. Be careful, spaces in XML files are not enforced by the current formatter.

**Comment by tomas-knap** [comment]
TODO: How to automate checking of spaces in XML files?

**Comment by mkl-eea-sk** [comment]
> Solution: Use spaces everywhere. Be careful, spaces in XML files are not enforced by the current formatter.

of course formatter enables you to enforce spaces. every reasonable IDE have this. in eclipse it is this configuration dialog:
![eclipsespacesxml](https://cloud.githubusercontent.com/assets/6399320/9111926/77ba8a48-3c4b-11e5-8075-57876b01e2dd.png)

**Comment by tomas-knap** [comment]
Please adjust your environment as @mkl-eea-sk proposes
