### ISSUE TITLE
migration of t-filesToRdf to 2.0 helpers

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#167]
there is available branch https://github.com/UnifiedViews/Plugins/tree/dpu/t-filesToRdf-1.5.1 , looks that some work is already done related to migration.
Is there something missing? Could be merged into develop (via pull request)?

**Comment by skodape** [comment]
It's not, there was a commit in develop. It would be probably easier to do the migration again then merge So I delete this branch and prepare new one.

**Comment by tomas-knap** [comment]
Duplicates #175
