### ISSUE TITLE
l-RdfToSparqlEndpoint not working with Apache Jena Fuseki

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#17]
https://cuni-test1.comsode.eea.sk/unifiedviews/#!PipelineEdit/14

Fuseki has separate endpoints for Graph Store, Read and Write. Loader tries to do select on a sparql update endpoint. Configuration must be separated.

**Comment by tomas-knap** [comment]
relates to #83, which must be solved first
