### ISSUE TITLE
t-filesToRdf already validates the RDF datasets

### ISSUE THREAD

**Issue by anisaR** [UnifiedViews/Plugins#170]
The problem is related to t-filesToRdf which correctly validates the RDF data. For example, consider da type date written in the document as: "01/01/2013"^^<http://www.w3.org/2001/XMLSchema#date>. This, is not a correct way of writing dates and as such the t-filesToRdf will return an error as shown in the screenshot. 
@tomas-knap, here we need to understand what to do with this kind of issues. We may avoid t-filesToRdf and leave the validation work to data quality dpus such as Q-ACC_1 or the RDFUnit dpu. In alternative, we can leave the  t-filesToRdf but this issue will not allow the running of the whole pipeline. 

![screen shot 2015-03-25 at 18 32 35](https://cloud.githubusercontent.com/assets/4330270/6830944/95ea3df2-d31d-11e4-8d0c-6605a4044fe8.png)

**Comment by jindrichmynarz** [comment]
Rather than trying to use a fault-tolerant RDF parser that prepares RDFDataUnit (without raising an exception on malformed data) for the RDF syntax validator DPU, I'd go with having FilesDataUnit piped as the input of the RDF syntax validator DPU. Is that possible?

**Comment by tomas-knap** [comment]
Yes, the validation DPU should take the file as the input
