### ISSUE TITLE
Custom DPU request: l-loadToParliament for loading data to Parliament RDF store

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#171]
This is a request for custom DPU l-loadToParliament for loading data to [Parliament RDF store](http://parliament.semwebcentral.org/). The DPU should be able to perform what is analogous to this curl command:

```bash
curl -X POST -F "dataFormat=RDF/XML" -F "statements=@08_UNESCO.rdf" http://localhost:8080/parliament/bulk/insert
```

On its input, it will receive a FilesDataUnit that will be serialized to the `statements` parameter. The DPU's configuration dialog will contain:

* Bulk upload endpoint URL (e.g., http://localhost:8080/parliament/bulk/insert)

Additionaly, if it's not possible to get from the FilesDataUnit or we don't want to rely on Parliament's format auto-detection, the configuration dialog should allow the user to specify the format of the uploaded data. The formats supported by Parliament include "N3", "TURTLE", "N-TRIPLES" and "RDF/XML".

The implementation will be most likely done via an HTTP client. However, the [Parliament user guide](http://parliament.semwebcentral.org/ParliamentUserGuide.pdf), page 8, figure 2.2., mentions that it's possible to use `com.bbn.parliament.jena.joseki.client.RemoteModel` class to upload a Jena model using a single method call. We could investigate whether Parliament also supports Sesame models (~ RDFDataUnit).

**Comment by mkl-eea-sk** [comment]
What is deployment setup of Parliament? Is it quickstart shell script running? Joseki or Sesame covered?

**Comment by jindrichmynarz** [comment]
See section 2.1.1 of the [user guide](http://parliament.semwebcentral.org/ParliamentUserGuide.pdf) (p. 5-6). Basically, all you need to do is to run a shell script. Joseki is included for the SPARQL endpoint. More details about interacting with Parliament via libraries can be found in section 2.1.2 of the user guide.

**Comment by mkl-eea-sk** [comment]
I was questioning since it may be deployed as Sesame Sail under Sesame server. In that case, the ordinary Sail loader would be sufficient. And we have also this task: https://github.com/UnifiedViews/Plugins/issues/17 and this https://github.com/UnifiedViews/Plugins/issues/169 and rework of l-rdfToSparql... it would make sense to join what can be joined into one piece of code.

**Comment by jindrichmynarz** [comment]
We discussed this with @hanecak and @tomas-knap and the resolution was to make this DPU specific to Parliament. Generic loader to SPARQL endpoints can be done by wrapping the [SPARQL 1.1 Graph Store HTTP Protocol](http://www.w3.org/TR/sparql11-http-rdf-update/), which is supported by many endpoints (Virtuoso & Fuseki included) but Parliament (i.e. Joseki) doesn't support it. There's already [a DPU](https://github.com/mff-uk/DPUs/tree/master/dpu/l-graphStoreProtocol) supporting this protocol.

**Comment by mkl-eea-sk** [comment]
OK. Sorry for thinking too much.

**Comment by skrchnavy** [comment]
Proposed name of DPU: l-filesToParliament (inspired by l-filesToVirtuoso).
@tomas-knap  and @jindrichmynarz please provide feedback.

**Comment by jindrichmynarz** [comment]
I think the name's fine.

**Comment by mkl-eea-sk** [comment]
How can one use "Parliament's format auto-detection" ? What is example curl in this case?

**Comment by jindrichmynarz** [comment]
`dataFormat=AUTO`:

```bash
curl -X POST -F "dataFormat=AUTO" -F "statements=@08_UNESCO.rdf" http://localhost:8080/parliament/bulk/insert
```

**Comment by jindrichmynarz** [comment]
Compiles fine and uploads data without problems.

However, I realized I've forgotten to specify the option to load data into a specific named graph. In its current form the DPU loads data into the default graph. But in most cases it's necessary to separate datasets into different named graphs. Using the Parliament bulk loader, named graph can be specified `graph` parameter:

```
curl -X POST -F "graph=http://example.com" -F "dataFormat=RDF/XML" -F "statements=@08_UNESCO.rdf" http://localhost:8080/parliament/bulk/insert
```

Can you extend the DPU to add this parameter?

Copy-pasted [README](https://github.com/UnifiedViews/Plugins/blob/feature/l-filesToParliament/l-filesToParliament/README.md) from l-filesUpload should be updated to describe the DPU's function.

**Comment by mkl-eea-sk** [comment]
Graph parameter added, you may give it a try.

**Comment by jindrichmynarz** [comment]
I used the DPU compiled from 152588c5028201dc059ed0b3f13a353bccbc47fc, unticked "Per graph mode" and filled in the target graph, but still the DPU loaded the data into the default graph and not the named graph specified. Is the graph parameter added properly?

**Comment by mkl-eea-sk** [comment]
I don't know, this works for me. May be call me using skype.
When the loading is in per-graph mode, the graphname is:
1. VirtualGraph 
2. internal RDF store graphname
When the loading is in one-graph mode, the graphname is:
1. graph name from configuration

**Comment by jindrichmynarz** [comment]
After a call with @mkl-eea-sk I discovered that the issue was probably caused by some glitch in UV front-end, because when I removed the files unpacked from its WAR, reloaded UV, and re-tested this DPU, it worked out fine.

So far I tested it on 3 datasets, all of which loaded fine, so I'm closing this issue.

**Comment by skrchnavy** [comment]
Pull request #205 not finalized, so reopened

**Comment by mkl-eea-sk** [comment]
Well, so what are we waiting for?

**Comment by tomas-knap** [comment]
#205 merged, closing
