### ISSUE TITLE
FilesToRDF: useless debug message

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#172]
![image](https://cloud.githubusercontent.com/assets/718827/6866008/0a05b372-d474-11e4-93fb-795bcc4b4187.png)

When extraction from one file fails, this message is shown. Instead of the filename, I see %s

**Comment by farky** [comment]
is it still reproducible? because for me not and it looks like changes from 29.3.2015 on the FileToRDF.java should fix this issue also.

**Comment by skrchnavy** [comment]
@jakubklimek please check

**Comment by skrchnavy** [comment]
@jakubklimek please check and provide answer.

**Comment by skrchnavy** [comment]
@tomas-knap please move to proper state (to close or to reopen)
