### ISSUE TITLE
e-rdfFromSparql has to be reworked

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#178]
So far, e-rdfFromSparql was not update to helpers 2.0 because updating the DPU would take more effort than rewriting it. So we should rewrite it using helpers 2.0.

TODO: Add reference to the @skodape DPU in mff-uk/DPUs which may be used as a base.

**Comment by tomas-knap** [comment]
Could be based on: 

https://github.com/mff-uk/DPUs/blob/master/dpu/e-sparqlEndpoint/src/main/java/cz/cuni/mff/xrg/uv/extractor/sparqlendpoint/SparqlEndpoint.java
(uses classes https://github.com/mff-uk/DPUs/tree/master/libs/service-external/src/main/java/cz/cuni/mff/xrg/uv/service/external)

**Comment by tomas-knap** [comment]
Or VirtuosoRepository (from Virtuoso provider lib) could be used instead of HTTP Reposiotyr (openRDF API). Both should use the same Repository API (from openRDF API)

**Comment by mkl-eea-sk** [comment]
VirtuosoRepository handles Virtuoso, not SPARQL endpoint. HTTP 
Repository handles Sesame(on Tomcat). SPARQLRepository 
(http://rdf4j.org/sesame/2.7/apidocs/org/openrdf/repository/sparql/SPARQLRepository.html) 
handles SPARQL endpoint.

**Comment by tomas-knap** [comment]
Quick solution: Move https://github.com/mff-uk/DPUs/blob/master/dpu/e-sparqlEndpoint/src/main/java/cz/cuni/mff/xrg/uv/extractor/sparqlendpoint/SparqlEndpoint.java to UV/Plugins, rename it to e-rdfFromSparql2, adjust README. 

The mff-uk/DPUs also uses classes https://github.com/mff-uk/DPUs/tree/master/libs/service-external/src/main/java/cz/cuni/mff/xrg/uv/service/external - such classes should be also moved to UV/Plugins - the sources of such library should be available in UV/Plugins/libs/xx. 

Note: Please remove from mff-uk/DPU/e-sparqlEndpoint and the lib, so that it is not accidentally update on two places in the future.

**Comment by tomas-knap** [comment]
Note: e-rdfFromSparql2.0 will not posses all the feature as the previous one - we will add these feature as they will be needed. e-rdfFromSparql1.X was far too complicated for any maitenance and overloaded with features.

**Comment by mkl-eea-sk** [comment]
See this changes https://github.com/UnifiedViews/Plugins/compare/develop...feature/e-rdfFromSparql2?expand=1

How should I properly test moved code?

**Comment by tomas-knap** [comment]
Not yet prepared for testing. @skodape please mark as "ready for test" when it is moved to UV/Plugins

**Comment by tomas-knap** [comment]
@skodape : To supplement the discussion from yesterday, e-rdfFromSparql uses two classes which are packed in mff-uk/DPUs supporting library (because they are also used by other DPUs in mff-uk/DPUs repository. 

Solution proposed: Make it simple - Put these two classes directly to e-rdfFromSparql DPU. If we later in the future create/adopt further DPUs in UV/Plugins using these two classes as well, we may expose the common functionality to UV/Plugins-libs repo. Minor disadvantage is that if certain bug is revealed in these two classes, it should be fixed in two places. On the other hand, having the classes for e-rdfFromSparql separated, it does not happen that any change to the classes required by mff-uk/DPUs does not influence in a wrong way e-rdfFromSparql. So lets start with a simple solution - put the 2 classes to e-rdfFromSparql DPU.

**Comment by skrchnavy** [comment]
Postponed to next release

**Comment by skrchnavy** [comment]
#241 shall be part of this issue.

**Comment by skrchnavy** [comment]
#266 ready for review
