### ISSUE TITLE
l-filesToVirtuoso: Issue #176 should be properly solved

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#179]
When finishing release UV 2.0, there was a bug https://github.com/UnifiedViews/Plugins/issues/176 in 
l-filesToVirtuoso. There was no time to fix it properly, so we just add possibility to turn off problematic section by using global properties, see https://github.com/UnifiedViews/Plugins/commit/71d2dd815acaa1411687d53c49de399ac5bf78e8

Solution: Solve the bug #176 properly.

**Comment by tomas-knap** [comment]
Relates to #176

**Comment by mkl-eea-sk** [comment]
How?

**Comment by tomas-knap** [comment]
DPUs should be primarily configured from their dialogs/config classes, not from a global configuration. So  there should be simply an option in the config dialog which turns off/on creation of users. By default turned off.

**Comment by mkl-eea-sk** [comment]
linked to this https://github.com/UnifiedViews/Plugins/pull/247
