### ISSUE TITLE
T-FilesFilter - Configuration dialog is hard to understand

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Plugins#18]
It is not clear to me what do the following mean:

1) Different kinds of fitlers - what is the meaning of each of them?
2) Customer predicate - what it is?

**Comment by tomas-knap** [comment]
@mkl-eea-sk Is this still relevant? Was it solved somehow?

**Comment by mkl-eea-sk** [comment]
Why me? @martinnec  should be questioned.

**Comment by skodape** [comment]
@tomas-knap Can you please reassign to me, as I'm updating the DPUs right now?

**Comment by skrchnavy** [comment]
@skodape see also this branch: feature/t-filesFilter

**Comment by skodape** [comment]
The original DPU, mentioned in this issue, no longer exists. If there is problem with current version, new issue can be created. 

@tomas-knap Can we close this as 'out of date' (new tag candidate?) ?
