### ISSUE TITLE
t-unzipper: failed to load dialog error

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#180]
When using t-unzipper from the develop branch (commit 0814a21e3c80e04df73e77c1bdd0d6d2ba79b7af), the DPU fails to load its dialog upon opening.

![screen shot 2015-04-07 at 08 29 26](https://cloud.githubusercontent.com/assets/198642/7018069/488eac2c-dd00-11e4-9f93-a090bacf6ddc.png)

Also note the typo with the double apostrophe in the error message.

**Comment by eea01** [comment]
I repaired the message, but I was not able to reproduce DPU load fail. Tested on clean installation of latest versions of UV, Plugin-DevEnv and t-unzipper plugin.

**Comment by skrchnavy** [comment]
above fix in UnifiedViews/Core@29217c6b1defa50494ffce5662f71ce0022b82e0

**Comment by jindrichmynarz** [comment]
The fixed DPU works fine in the latest Core version.

**Comment by skrchnavy** [comment]
@jindrichmynarz what versions of Core do you have (commit number, etc)?

**Comment by jindrichmynarz** [comment]
I'm using Core from [this commit](https://github.com/UnifiedViews/Core/commit/3e3efd66a4d19e26a5c14b36544c33eefac9fa71).
