### ISSUE TITLE
Java package name shall be eu.unifiedviews.plugins.* for DPUs

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#181]
Currently thease DPUs are in package cz.cuni.mff.xrg.uv.*
* t-sparqlConstruct
* t-sparqlUpdate
* t-tabular
* t-xslt

They shall be migraterd to eu.unifiedviews.plugins.*

**Comment by tomas-knap** [comment]
t-xslt will not be updated as the package is used in the configuration of the DPU - so it would be more work than just renaming packages. Since #181 is not that crucial and must be quickly solved, t-xslt will not be updated.

**Comment by skrchnavy** [comment]
@mbl-eea-sk be aware of proper migration of configuration from current package name.

**Comment by mbl-eea-sk** [comment]
Created pull request https://github.com/UnifiedViews/Plugins/pull/249
