### ISSUE TITLE
t-filesFindAndReplace reads all its input as UTF-8

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#184]
t-filesFindAndReplace reads all its input as if it was encoded in UTF-8. Character set is taken from DPU configuration (see [here](https://github.com/UnifiedViews/Plugins/blob/master/t-filesFindAndReplace/src/main/java/eu/unifiedviews/plugins/transformer/filesfindandreplace/FilesFindAndReplace.java#L116)), however it's not configurable (see [here](https://github.com/UnifiedViews/Plugins/blob/master/t-filesFindAndReplace/src/main/java/eu/unifiedviews/plugins/transformer/filesfindandreplace/FilesFindAndReplaceConfig_V1.java#L13)) and instead it's fixed to "utf8".

For example, I try to use this DPU on a [Windows-1250-encoded file](http://www.uvo.gov.sk/documents/10157/1544912/UVO_rozhodnutia_kontrola.csv) and pass it to t-tabular. However, the file ends up mangled due to being incorrectly read as UTF-8 and t-tabular cannot parse it.

The solution might consist of:

1. Allowing users of the DPU to configure character set.
2. Auto-magically detecting input character set and convert it to UTF-8.
3. Provide an extra DPU for converting various character sets to UTF-8 and set a "contract" of DPUs to accept only UTF-8-encoded input.
4. Anything more clever.

**Comment by skrchnavy** [comment]
@jindrichmynarz please check if it works for you with above change. (if you could, please test also migration from version 2.0.0 to current.

**Comment by jindrichmynarz** [comment]
The DPU compiled from 5d33ddb78d8a67d4e81862271b633d4bd50f2ca3 and run in Core compiled from [the newest commit](https://github.com/UnifiedViews/Core/commit/791cdce39008b4553e068ba1e2f42a90b7001164) works fine.
