### ISSUE TITLE
tabularToRelational: character encoding should be in a selection list

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#192]
Based on #129.
Expected is to have selection list (combo box) to select encoding

**Comment by skrchnavy** [comment]
@eea02 : is pull request #212 related to this requirement?

**Comment by eea02** [comment]
yes, I did not know about this issue

**Comment by eea02** [comment]
Fixed in commit: b25d2310e853ab3f6807393a420084ea0fe49a44
