### ISSUE TITLE
t-tabular: character encoding should be in a selection list

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#193]
Based on #129.
Expected is to have selection list (combo box) to select encoding

**Comment by mkl-eea-sk** [comment]
I wonder about this:
https://github.com/UnifiedViews/Plugins/compare/develop...dpu/t-Tabular-2.2.0
hmmmm

**Comment by mkl-eea-sk** [comment]
this is already in develop.

**Comment by skrchnavy** [comment]
@tomas-knap  please check commit e42b39754218829d2adceb16b6cbd319e75b17cf if this issue is fixed. (not clear how it was merged into develop, proper branch exists).

**Comment by mkl-eea-sk** [comment]
There is an issue - if any user had filled in any custom character set which is not in our list of supported charsets, this updates breaks his pipeline. So we will restart our effort to fix this issue in proper (editable combo box for example).

**Comment by mbl-eea-sk** [comment]
Encoding selection list now accepts manually typed additional encoding.

**Comment by skrchnavy** [comment]
#250 merged so this is fixed
