### ISSUE TITLE
DPU Request: Transformer: Text file merger

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#2]
DPU Request: Transformer: Text file merger

Example: XSLT -> Thousands of text (CSV) files. Need to merge them into one.

**Comment by skrchnavy** [comment]
@jakubklimek: is there special request for handling csv files?
for example  if header row shall be checked, if header row is present in all files, if content shall be checked for consistency (number of columns for exapmple, etc.

@skodape : is this DPU without any input and output? Is it extractor or loader? I would expect that this DPU shall just receive long list of single files and provide one file at the output as 'cat \<inputfiles*\> > \<outputfile>'

**Comment by tomas-knap** [comment]
@jakubklimek On which pipelines is this DPU required?
