### ISSUE TITLE
L-filesUpload: Output should not be mandatory, but optional

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#204]
To reproduce: 
1) Create pipeline with l-filesUpload at the end (no edge from l-filesUpload)
2) click Validate
3) It shows that mandatory output of l-filesUpload is missing

![screen shot 2015-04-27 at 10 00 11](https://cloud.githubusercontent.com/assets/3014917/7343675/9144af92-ecc4-11e4-98dd-8fa4b704df9e.png)

Solution: Output of l-filesUpload must be optional, not mandatory.

**Comment by skrchnavy** [comment]
@farky please update version of DPU (2.0.2-SNAPSHOT) in pom and also in Readme.md

**Comment by mkl-eea-sk** [comment]
beware of this commit:
https://github.com/UnifiedViews/Plugins/commit/5d09e5533d639fd52a5251de46c134ba835621ad
it changes names of DataUnit inputs and outputs... pipelines created for old DPU will render as invalid after this commit ... why the hell some needs to rename data units (in this way from good name "filesInput" to "input". Well, try to use our tool and you will see that you do not know what to connect where...)

**Comment by mkl-eea-sk** [comment]
@skrchnavy as the DPU is now in 2.1.0-SNAPSHOT i have updated readme.md accordingly.

**Comment by mkl-eea-sk** [comment]
see this https://github.com/UnifiedViews/Plugins/pull/248

**Comment by skrchnavy** [comment]
currently all DPUs are in 2.1.0 so my coment is obsolete

**Comment by mkl-eea-sk** [comment]
yes, but i have fixed readme.md accordingly (as the output was not noted there). so this issue is ready for test (and merge https://github.com/UnifiedViews/Plugins/pull/248).
my comment about renaming data units is not relevant for this issue, just for future - lets be aware of it - we must not rename data units - it breaks existing pipelines.

**Comment by skrchnavy** [comment]
@tomas-knap please check the renaming of filesOutput data unit, it was already released with that name by my check of code.

**Comment by tomas-knap** [comment]
Since the input data unit name is "input" for 2.X version of this DPU for the last 3 months, we leave this name for input (if we change it, we cause that the pipelines have to be adjusted because the mapping of inputs->outputs will be invalid). Preparing guideline for naming data units, as currently do not have one patter (most of the DPUs either use {input|output} or {filesInput|rdfInput|...}

**Comment by tomas-knap** [comment]
So this may be closed when https://github.com/UnifiedViews/Plugins/pull/248 is merged

**Comment by skrchnavy** [comment]
@tomas-knap output was renamed in this version, so this have to be decided, if we revert back to filesOutput or leave it as output. @mkl-eea-sk  warning is that changing the name to output would require pipeline redrawing .

**Comment by skrchnavy** [comment]
@tomas-knap my comment is obsolete I checked in more details how it was in latest release and names are input and output, so this is correct.

**Comment by skrchnavy** [comment]
Resolves #248
