### ISSUE TITLE
T-GZipper: support for gzip compression

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#210]
Create new DPU or adjust existing (t-zipper) with support for gnu zip compression to compress files into gzip form. Adjust also Readme.md properly.

**Comment by tomas-knap** [comment]
New DPU should be created, as @jakubklimek  requested

**Comment by tomas-knap** [comment]
Btw. what is the requirement for this? Is it EDEM req?

**Comment by skrchnavy** [comment]
There is no specific requirement but it is triggered by #211 to have both extractors and loaders.
