### ISSUE TITLE
T-GUnzipper: support for gzip compression

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#211]
To create new DPU or to extend T-Unzipper with support for gnu zip compression method to uncompress also gzip files.
Also Readme.md to be updated.

**Comment by tomas-knap** [comment]
@jakubklimek and @skodape prefers to have two separate DPUs. As they are users in this case, please prepare extra DPU for handling gzip compression/decompress.

**Comment by skrchnavy** [comment]
Other option is to extend filesDownload as VFS supports extract from different zip formats (https://commons.apache.org/proper/commons-vfs/filesystems.html) but requires to add optional input.

**Comment by skrchnavy** [comment]
@jindrichmynarz  @jakubklimek  @skodape : is also tar.gz/tgz support required?

**Comment by jindrichmynarz** [comment]
It's not required in the current scope of Slovak COMSODE datasets. However, I think it would be very useful to support tar archives as well.

**Comment by tomas-knap** [comment]
New DPU shall be prepared, we should not extend existing. 1) This is request of the users 2) Such simple DPU are better reusable, easier to be configured.

**Comment by tomas-knap** [comment]
Regarding unzipper, there is already a DPU (https://github.com/mff-uk/DPUs/tree/master/dpu), which does unzipping. It is not updated to latest helpers, but may be use as a base.

**Comment by tomas-knap** [comment]
Btw. what is the requirement for this? Is it EDEM req?

**Comment by jindrichmynarz** [comment]
OK, I haven't seen the [t-unZipperGZip](https://github.com/mff-uk/DPUs/tree/master/dpu/t-unZipperGZip) DPU before. It would be great if it could be made usable with the latest UV.

Regarding the requirements, GZip decompression is required by 2 Slovak COMSODE datasets and datasets that we want to link in the COMSODE pilot with SAŽP (see [COMSODE-987](https://team.eea.sk/jira/browse/COMSODE-987)).

**Comment by mkl-eea-sk** [comment]
Try
```
gz:tar:file:///extra/data/tryVfs/archive.tar!/tardir/content.txt.gz!content.txt
```
as file uri in e-filesDownload.
this is gz.tar (crazy :), where .tar contains /tardir/content.txt.gz, which ungzipped resolves to content.txt.
Well, this is usefull to name one file inside gzip (one would have to name all of them to extract them using e-filesDownload).

But if in hurry, this may help.

**Comment by jindrichmynarz** [comment]
Does this work for remote URLs as well? For example, can I use e-filesDownload to download and decompress <https://www.sk-nic.sk/documents/registratori.txt.gz>?

However, this is not very user friendly and we're not in such a hurry, so I think we should go for a different approach.

**Comment by mkl-eea-sk** [comment]
done here: https://github.com/UnifiedViews/Plugins/tree/feature/dpu_gunzipper/t-gunzipper
if in hurry, use this. i will extend it further after we resolve other high prio issues.

**Comment by mkl-eea-sk** [comment]
https://github.com/UnifiedViews/Plugins/pull/213

**Comment by jindrichmynarz** [comment]
Tested and works fine.

**Comment by skrchnavy** [comment]
#213 accepted, so closing
