### ISSUE TITLE
README of l-filesToVirtuoso should describe how the DPU needs to receive its input

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#218]
README of l-filesToVirtuoso should document how the DPU needs to receive its input. There's no explicit input and output. Input needs to be specified as a path on file system on the server where Virtuoso is running. The documentation may include that in this setup the DPU is typically run with the `run_after` edge connected to a DPU that loads data to the filesystem.

Relates to #208.

**Comment by mkl-eea-sk** [comment]
OK, but if it is not absolutely necessary, I would recommend you to not use this dpu, but the rdfToVirtuoso version.

**Comment by jindrichmynarz** [comment]
That would be fine for smaller datasets, but for larger datasets we want to avoid loading the data into the internal store of UnifiedViews. For example, this is the case of [Geonames.org](https://github.com/comsode-uv-plugins/t-geonamesOrgToTriples), which has more than 10 GB in size and millions of triples.

**Comment by mkl-eea-sk** [comment]
OK< well. it is questionable, if we should provide filesdataunit as input to this dpu. it could be done, could make things simpler for pipeline designer (at least for one ODN running on single host)
