### ISSUE TITLE
T-SparqlSelect - configuration dialog - step configuration panel should have margin

### ISSUE THREAD

**Issue by farky** [UnifiedViews/Plugins#220]
T-SparqlSelect - configuration dialog - step configuration panel should have margin
![2015-05-14_2226](https://cloud.githubusercontent.com/assets/131974/7641542/b4aad564-fa8a-11e4-99c7-d7fe85725e41.png)

**Comment by skrchnavy** [comment]
@tomas-knap please briefly check, it is fix in develop, when no comments it can be closed directly.

**Comment by mkl-eea-sk** [comment]
it is here https://github.com/UnifiedViews/Plugins/commit/5e2a23ba4a49171daffd698e713c38252e017dc8
it works
![screenshot - 07022015 - 07 05 16 am](https://cloud.githubusercontent.com/assets/6399320/8470269/bcca8536-2088-11e5-8596-40ea877879f5.png)
