### ISSUE TITLE
t-tabular: Cannot save the default configuration for Excel input

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#223]
Using the latest develop version of t-tabular (5e2a23ba4a49171daffd698e713c38252e017dc8) it is not possible to save the DPU configuration for Excel input. When you choose the Excel input and try to save the configuration, you will see this error, which will prevent you from saving the configuration:

```
Failed to save configuration. Reason: Wrong format of lines to skip.
```

It's only possible to save the DPU configuration if you enter a number of lines to skip. The default value of the lines to skip parameter should therefore be 0 instead of empty string.

**Comment by skrchnavy** [comment]
@skodape please check what is the root cause of this issue.

**Comment by skodape** [comment]
Please see #226, where I added some more details and propose a solution.

**Comment by skodape** [comment]
Also @jindrichmynarz could you try tabular from that branch and provide feedback, probably to the puil request?

**Comment by jindrichmynarz** [comment]
[Tested](https://github.com/UnifiedViews/Plugins/pull/226#issuecomment-103397342) and works fine.
