### ISSUE TITLE
t-filesToRdf cannot set named graph URI 

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#225]
@mkl-eea-sk writes in #224:

This is bug in FilesToRdf, which does not set (nor even let you choose) the VirtualGraph metadata. Symbolic name, as such, cannot be used in rdfToVirtuoso as Graph name, since it may not be http:// URI. It is just plain string (Unicode enabled).
rdfToVirtuoso has two options what to use in per graph mode:
- virtual graph metadata
- internal graph name

**Comment by jindrichmynarz** [comment]
This apparently no longer seems to be an issue, so I'm closing it.

**Comment by skrchnavy** [comment]
@jindrichmynarz was it fixed somehow or is this issue not valid?

**Comment by jindrichmynarz** [comment]
This issue was valid, but I cannot recreate it with the newer version of t-filesToRdf and l-rdfToCkan that are in ODN 1.0.2. This means that the issue was fixed either in t-filesToRdf or l-rdfToCkan. Unfortunately, I don't know which one is it.

Moreover, I prompted a discussion with @tomas-knap related to this issue. The problem is that we currently use 2 approaches to set the named graph URI and we should probably unify them.

1. The first approach is to enable setting named graph URI in the DPU that produces RDFDataUnit (e.g., t-filesToRdf). Then the named graph URI is available as a symbolic name.
2. Alternatively, named graph URI can be set in loaders to RDF store (e.g., l-filesToParliament).

If we decide to adopt the first approach, then all DPUs that produce RDFDataUnit must allow to set named graph URI. Alternatively, adopting the second approach would imply that all loaders to RDF stores must allow to set named graph URI.

These two approaches need to be unified, which is why I asked @tomas-knap to decide.

This is already causing us problems in pipelines. For example, a pipeline produces RDFDataUnit via t-sparqlConstruct (currently, no way to set named graph URI), which is loaded via l-rdfToCkan (currently, no way to set named graph URI). Consequently, in such case you cannot directly set named graph URI explicitly (a work-around is to serialize RDFDataUnit to file via t-rdfToFiles and back to RDFDataUnit via t-filesToRdf, which allows you to set named graph URI).

**Comment by skrchnavy** [comment]
I think both approaches shall be supported but preferable more important is setup graph name in loaders, because the loaders could write also to external SPARQL endpoints where the name of temporary graph during processing would be insufficient (virtuoso as temporary store for multiple pipelines and virtuoso with final data filled in also from other sources.)

**Comment by jindrichmynarz** [comment]
I'd like to record a good point from email conversation with @mkl-eea-sk, who argued that being able to set explicit named graph URIs in DPUs producing RDFDataUnits would make querying the data easier. Indeed, this covers a case that I've already discussed with @tomas-knap. When a pipeline combines multiple datasets (e.g., linking them) it is beneficial to be able to distinguish the datasets via their named graph URIs in SPARQL queries. This way you can avoid querying the union of the datasets, which may be (1) insufficient for identifying the resources you want to find, (2) computationally more demanding as a larger dataset needs to be searched.

**Comment by skrchnavy** [comment]
I agree that is is good also to name graphs for temporary store (n case using virtuoso as temp store there could be also issues with parallel running pipelines using same naming)
But also second point is important, when you external RDF store requires different graph name then the one used localy.

So I think both shall be user defined with some reasonable defaults.

**Comment by mkl-eea-sk** [comment]
just to clarify, there are three graph names:
- internal rdf store graph URI (currently internally generated, can by 
programatically selected in DPUs, but we do not provide this option to 
users via GUI in DPUs) for symbolic name
- virtualgraph metadata - this is just a metadata about symbolic name, 
rdf loaders use this one as first option for external graph name when 
loading in per-graph (per-symbolic name) mode (if virtualgraph is not 
present they use internal rdf store graph URI).
- external graph name - name of graph when put outside of UV.
in general we want:
external graph name == virtualgraph metadata
internal rdf store graph URI - not leak outside of UV, prevent naming 
conflicts between pipelines (currently each pipeline has own storage so 
this is not an issue)

now we have situation where user works with two names for RdfDataUnit Entry:
- symbolic name
- virtual graph
as this discussion already happened nearly a year ago (debate on meaning 
of symbolic names), they are here and we have to cope with it.
I am interested in what does user (Jindrich) think of concept of 
symbolic name and if he finds it suitable or not and how would he 
preffer to name graphs in rdfdataunit.

Same situation holds for files data unit, we have symbolic name, virtual 
path and external path. But with files, the situation has converged to 
use symbolicName == virtual path (of cource, once we convert aaa.rdf 
from file to graph, we get graph with symbolic name "aaa.rdf" and thats 
crazy).

i am listening...

**Comment by jindrichmynarz** [comment]
As a user I don't care about how are the data units named internally. I would even argue that exposing this via the DPU configuration can be confusing.

What I care about is:

1. Being able to specify file name (or file path, respectively) for FileDataUnit or named graph URI for RDFDataUnit when loading the data.
2. Being able to distinguish data from different RDFDataUnits in SPARQL queries. This can be done by allowing the user to explicitly name the graphs or by exposing the auto-generated graph names somehow.

**Comment by jindrichmynarz** [comment]
@tomas-knap: Was a decision taken to address this? I have run into the general issue of where to specify named graph URIs in OpenDataNode/UVPlugin-rdfToCKAN#3, so I would like to know what is the chosen approach. Should I open a separate issue for this?

Ultimately, we should create issues either for all DPUs that produce RDFDataUnit and cannot set its named graph URI or all DPUs that load RDFDataUnit and cannot set its named graph URI.

**Comment by jindrichmynarz** [comment]
As the discussion is no longer about t-filesToRdf in particular, but about setting named graph URIs in general, I moved it into a separate issue #268, so that we can close this one.

**Comment by skrchnavy** [comment]
@jindrichmynarz what is resolution of this issue (original report) ?

**Comment by jindrichmynarz** [comment]
The issue of t-filesToRdf was resolved by some previous commit (as mentioned above in [here](https://github.com/UnifiedViews/Plugins/issues/225#issuecomment-109305826)).

**Comment by skrchnavy** [comment]
Based on above comment this issue was solved in 2.0.1 because it was not reproducible there
