### ISSUE TITLE
l-filesUpload: The DPU execution thread ends in non-standard way

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#227]
In one of my pipelines l-filesUpload fails with the following error (copied from the UnifiedViews execution monitor):

```
Type: PIPELINE_ERROR
Short message: DPU execution failed
Message:
The DPU execution thread ends in non-standard way
```

Sadly, `backend_err.log` is empty, so I cannot provide more details with a stack trace. Any suggestions about what may cause this issue?

I'm using l-filesUpload 2.0.1 that comes with the OpenDataNode 1.0.1 via the odn-simple Debian package.

**Comment by skrchnavy** [comment]
Do you have enough memory or disk space?

**Comment by jindrichmynarz** [comment]
Thanks! That's a good tip. It seems that the problem can have something to do with disk space, of which 91 % is used. 

It seems that the cause of the problem is excessive logging of UnifiedViews discussed in comsode-uv-plugins/t-geonamesOrgToTriples#1. Even when not run in the debug mode, this DPU produces GBs of logs on the filesystem and in the database back-end. For example, if I list the largest tables in PostgreSQL, the first ones capture logs:

```
                      relation                       |  size
-----------------------------------------------------+---------
 public.logging                                      | 3583 MB
 public.ix_LOGGIN_relative_id                        | 530 MB
 public.ix_LOGGING_dpu                               | 473 MB
 public.ix_LOGGIN_execution                          | 473 MB
 public.logging_pkey                                 | 373 MB
```

Unfortunately, UnifiedViews doesn't provide any way how to safely delete past pipeline executions and logs (UnifiedViews/Core#362). I think this is a fairly important feature.

**Comment by mkl-eea-sk** [comment]
lets transfer whole pipeline

**Comment by mkl-eea-sk** [comment]
logging table can be truncated manually without any harm (you lost logs 
from all pipeline executions)

**Comment by jindrichmynarz** [comment]
What about the other logging tables: can I truncate them as well? It would be great if there was an SQL script to delete all temporary data that UnifiedViews stores in its database back-end.

**Comment by mkl-eea-sk** [comment]
Ask skodape, I am not aware of, that there are more than one logging table.

**Comment by jindrichmynarz** [comment]
I assume the tables `public.ix_LOGGIN_relative_id`, `public.ix_LOGGING_dpu`, `public.ix_LOGGIN_execution` etc. are also related to logging. @skodape, can you clarify?

**Comment by jindrichmynarz** [comment]
I discussed this with @skodape and found out that I had overlooked that these are indices and not tables. They are truncated as a result of doing `TRUNCATE logging;`.

**Comment by jindrichmynarz** [comment]
In conclusion, it seems that this issue was caused by lack of disk space. Therefore I'm closing it.
