### ISSUE TITLE
Enable to clear loaded graphs in l-loadToParliament

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#230]
Extend [l-filesToParliament](https://github.com/UnifiedViews/Plugins/tree/develop/l-filesToParliament) to enable to clear old data from graphs new data is loaded in. The requested functionality is the same as l-filesToVirtuoso "Clear destination graph before loading" option (see [here](https://github.com/UnifiedViews/Plugins/blob/master/l-filesToVirtuoso/src/main/java/eu/unifiedviews/plugins/loader/filestovirtuoso/VirtuosoLoader.java#L141-L146)).

Clearing old data from graphs should be done via SPARQL Update `CLEAR GRAPH` operation (NB: Without using Virtuoso-specific `DEFINE sql:log-enable 3`). If the DPU's user checks in the "Clear destination graph before loading" option, then `CLEAR GRAPH <graph URI>` should be executed for each graph that new data is loaded into.

SPARQL Update operation should be sent as POST request to the `/parliament/sparql` endpoint. The URL-encoded SPARQL Update operation should be sent in the `update` parameter. For example, this is how a graph can be cleared using curl: `curl -X POST --data-urlencode "update=CLEAR GRAPH <URI grafu>" http://localhost:9090/parliament/sparql.`

The configuration of the current DPU version requires the user to fill in the Bulk upload endpoint URL. However, SPARQL Update endpoint URL is needed for the proposed functionality. Therefore, the configuration of the DPU should be generalized to the root where Parliament runs (typically http://localhost:8080/parliament/). Given the root URL the required endpoints are:

- SPARQL Update endpoint = root URL + "sparql"
- Bulk upload endpoint = root URL + "bulk/insert"

Note: The described functionality is general to all loaders to RDF stores, which could warrant putting it into /UnifiedViews/Plugins-DevEnv. However, for the simplicity sake, we will implement in directly in this DPU. Should several other DPUs need this functionality, it will be moved into /UnifiedViews/Plugins-DevEnv.

**Comment by jindrichmynarz** [comment]
This was fixed on the `feature/parliamentdeletegraph` feature branch, but that branch was deleted and it seems that it wasn't merged in the develop branch.

**Comment by skrchnavy** [comment]
looks that #233 was closed without merge. @mkl-eea-sk was it accidentally (then we will restore the branch) or intentionally?

**Comment by mkl-eea-sk** [comment]
mistake

**Comment by skrchnavy** [comment]
#233 PR reopened

**Comment by mkl-eea-sk** [comment]
#233 PR closed
