### ISSUE TITLE
Create new DPU: e-DistributionMetadata

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Plugins#237]
Take this dpu https://github.com/mff-uk/DPUs/tree/master/dpu/e-distributionMetadata
move it here, rewrite it completely and make it work.

**Comment by mkl-eea-sk** [comment]
Adjustments needed for UV/Plugins metadataDistribution (adjusted CUNI version):

    No checkboxs "Get ... from dataset". If certain field is not specified, output metadata does not contain the corresponding predicated. 
    Set of supported fields - see the table above, column "Should be implemented in UV/Plugins distributionMetadata DPU?"
        Modified is computed automatically
        sparqlEndpoint not necessary
    It has to be differentiate whether metadata for data dump, SPARQL Endpoint or REST API CKAN resource are prepared 
        for each type different set of metadata available (see the last column in the table above)
    No input is needed for this DPU (the input was there because in CUNI version it may take certain metadata from dataset metadata)
    Note: Output format of metadataDistribution should be RDF, so that 1) most of the way of handling data may be reused, 2) it may be in UV/Plugins, as a DPU, which may be used not just in ODN context with CKAN loader after that 3) the outputted (RDF) data may be browsed.

**Comment by skrchnavy** [comment]
@mkl-eea-sk shall be this issue closed (#236 closed) or is it another issue?

**Comment by mkl-eea-sk** [comment]
resolved by merging this https://github.com/UnifiedViews/Plugins/pull/238 pull request
