### ISSUE TITLE
Cannot build E-RelationalFromSql

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#242]
When I try to build this one from develop, I get
```
[ERROR] Failed to execute goal on project uv-e-relationalFromSql: Could not resolve dependencies for project eu.unifiedviews.plugins:uv-e-relationalFromSql:bundle:2.1.0-SNAPSHOT: Could not find artifact com.oracle:ojdbc7:jar:12.1.0.2.0 in maven.eea.sk (http://maven.eea.sk/artifactory/public/) -> [Help 1]
```

**Comment by skrchnavy** [comment]
Please read https://github.com/UnifiedViews/Plugins/blob/develop/e-relationalFromSql/README.md file where is link to https://github.com/UnifiedViews/Plugins/blob/develop/e-relationalFromSql/BUILD.md describing this dependency problem due to licensing.

**Comment by skrchnavy** [comment]
@tomas-knap / @jakubklimek - can we close this issue as invalid or do you see it still as a bug?

**Comment by tomas-knap** [comment]
@jakubklimek Taking README into account, is it ok?

**Comment by skrchnavy** [comment]
Proposed solution is to include profiles into pom file of this DPU to be able to switch what drivers are bundled.
It shall be enough:
* to define profile for oracle
* to fill in combo box with jdbc driver selection based on configuration
** this could be in compile time or in runtime, what is possible.

**Comment by eea03** [comment]
Fixed in #270

**Comment by skrchnavy** [comment]
@eea03 / @tomas-knap Is there a way how we can in DPU indicate it is DPU with Oracle or without?

**Comment by eea03** [comment]
As discussed with @skrchnavy, this information is no so important in already built DPU as this does not have any impact on its functionality once it is built, it just has another supported database.

Important is that when whoever checks out and builds this DPU, he does not have to execute manual steps.

**Comment by eea03** [comment]
#270 approved and merged to develop, closing issue
