### ISSUE TITLE
Ungzipper strip extension .gz if present

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Plugins#253]
Regarding ungzipper, it should try to unzip any file (whether it is named xxx or xxx.gz) and if xx.gz was used, the resulting unzipped file is xxx. 
Taken from https://github.com/UnifiedViews/Plugins/pull/239#issuecomment-117303728

**Comment by skrchnavy** [comment]
commit 9646dc5d641d684f5826606c7998257d9cb7fafc resolves #253
