### ISSUE TITLE
Bad handling of Czech (and special) characters in file names

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#264]
When I extract local files with diacritics (and special characters) and then a DPU tries to access them, it accesses a urlencoded version which of course does not exist.

This can be either a bug in the DPU or in Core.
![bug cestina](https://cloud.githubusercontent.com/assets/718827/8591340/eddb4a6c-2627-11e5-9c50-970935fae27e.png)

**Comment by mkl-eea-sk** [comment]
Where I can find xls2csv sources?

**Comment by skrchnavy** [comment]
@jakubklimek  This shall be reported in repository where is affected DPU, xls2csv is not part of Plugins.
When it is problem of core, it shall be reported in Core repository.
I see it invalid.
