### ISSUE TITLE
t-unzipper: Label for checkbox „Do not prefix symbolic name“ is confusing for normal user

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#265]
In t-unzipper, there is checkbox „Do not prefix symbolic name“ which is a bit confusing for the normal user (normal user should not know anything about symbolic name).

Proposal: Change the label of the checkbox - in EN, SK. E.g to "Prevencia duplicitných názvov".

**Comment by skrchnavy** [comment]
Be careful to be backward compatible with up to date version.
Logic in GUI is to be changed (reverted) and configuration class shell be kept. So based on the requirement, checked checkbox shall have `false` value in configuration class.

Please properly document in code why this is implemented how is implemented.

Part of this task is improvement of documentation (readme.md + about.html)

**Comment by mkl-eea-sk** [comment]
https://imgflip.com/i/o0rzv
