### ISSUE TITLE
t-rdfGraphMerger: Prepare DPU which physically merges graphs

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#272]
Based on discussion in https://github.com/UnifiedViews/Plugins/issues/269, the goal is to prepare DPU which physically merges RDF data (t-rdfMerger only copies graphs from more input data units to one data unit). It should work as t-graphMerger (htps://github.com/mff-uk/DPUs/tree/master/dpu/t-graphMerger), so basically it means to take t-graphMerger from there, update pom.xml, ad SK loc. 

The name for the DPU: t-rdfGraphMerger

Also please provide the user with the possibility to define (in textbox in config dialog) VirtualGraph - metadata attached to the target merged graph, which may be used by loaders to automatically load to certain target graph. @mkl-eea-sk, how is it with l-rdfToCkan and similar, do they support correctly VirtualGraph?

**Comment by mkl-eea-sk** [comment]
rdfToCkan is ready for this
