### ISSUE TITLE
e-filesDownload: duplicate symbolic names generated

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#274]
e-filesDownload generates symbolic names from URL's path. The path is often non-unique, which results in an error. For example, there are cases in which downloaded resources are distinguished by query string. Consider downloading resources from the following URLs:

* <http://www.health.gov.sk/Zdroje?/Sources/datasety/1722/1722--kurz-PP-ku-dnu-31-10-2013/Health-1722-ku-dnu-31-10-2013.xml>
* <http://www.health.gov.sk/Zdroje?/Sources/datasety/1722/1722--kurz-PP-ku-dnu-30-09-2013/Health-1722-ku-dnu-30-09-2013.xml>

Doing so in a single instance of e-filesDownload results in an error `Duplicate entry found for symbolic name: /Zdroje`.

The method of generating symbolic names should be improved. Instead of just the URL's path, it should take into account the whole URL (e.g., by using its SHA1 hash).

I marked this as an enhancement, because it can be avoided by explicitly setting file names of the downloaded resources.

Context: I discovered this issue in e-filesDownload version 2.1.0.

**Comment by skrchnavy** [comment]
Based on UnifiedViews/Plugins#327 it seems this issue is again present in develop. @mbl-eea-sk to test

**Comment by mbl-eea-sk** [comment]
When I tried to download two files mentioned above without setting explicit name they were named correctly.

![filenames](https://cloud.githubusercontent.com/assets/12254192/9651715/7e0b6e60-5214-11e5-9626-c8fc8bb72019.png)

If I set the same explicit name for both them execution fails which is correct behavior as no OS filesystem allows to store two identically named files in the same folder.

**Comment by jindrichmynarz** [comment]
As I wrote in #327, I can no longer reproduce this issue, so I'm closing this for now.
