### ISSUE TITLE
l-filesToVirtuoso: improve usability of the configuration dialog

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#282]
Configuration dialog of l-filesToVirtuoso can be improved.

1. Virtuoso JDBC URL, username, and password may be filled with default values (as l-rdfToVirtuoso does).
2. "Include subdirectories" requires the user to type in either "true" or "false". This would be better of as a check-box.
3. Syntax of "File name pattern" should be documented.

Context: ODN 1.1.0

**Comment by mkl-eea-sk** [comment]
And what if it had Files Data Unit on input...
