### ISSUE TITLE
t-xslt: Increase the size of the "XSLT template" field

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#289]
Size of the "XSLT template" field in t-xslt is fairly small, which makes editing XSLT in it difficult. Editing XSLT directly is usually done when a UnifiedViews-specific adjustment needs to be done, such as replacing the `uuid` namespace with `java:java.util.UUID` by `uuid-functions` (see also #187). From the usability perspective it would be useful to be able to edit the XSLT in the DPU's configuration dialog more easily. This can be done by increasing the size of the "XSLT template" field. Currently, it is small, since a lot of space is occupied by "File extension" and "Number of extra threads" fields, which could easily fit one line instead of being block inputs spanning two lines:

<img width="753" alt="screen shot 2015-07-29 at 17 30 05" src="https://cloud.githubusercontent.com/assets/198642/8961775/8984a4f0-3617-11e5-9277-4b8b859b76be.png">

Moreover, the "XSLT template" field is not resizable.

As a side note, why is this field called "XSLT template" and not the more common "XSL stylesheet"?

Context: version 2.2.0 of t-xslt in ODN 1.1.0.

**Comment by mbl-eea-sk** [comment]
I do not encounter this problem as the size of TextArea is set to full:
https://github.com/UnifiedViews/Plugins/blob/master/t-xslt/src/main/java/eu/unifiedviews/plugins/transformer/xslt/XsltVaadinDialog.java#L84

Loaded template behaves properly.
![xlst](https://cloud.githubusercontent.com/assets/12254192/8977118/6216d648-3696-11e5-8caf-ca3b63028f8c.png)

**Comment by jindrichmynarz** [comment]
Yes, "XSLT template" field's `textarea` expands to the available space. My point was that there is not much available space left due to multiline inputs above. This is especially true for smaller screens. For instance, I encountered this on my 13" laptop.

Context: Tested in Google Chrome 44, Mozilla Firefox 39, and Safari 8.

**Comment by mbl-eea-sk** [comment]
Would be OK if the two text fields above take only one line side by side?

**Comment by jindrichmynarz** [comment]
It would be better.
