### ISSUE TITLE
t-rdfValidator: why transformer instead of QA DPU?

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#291]
Why is t-rdfValidator a transformer instead of a quality assessment DPU?

**Comment by skrchnavy** [comment]
It is implemented as a filter, doesn't report quality. DPU stopes when xml is not valid or only valid xml are forwarded to output.

**Comment by jindrichmynarz** [comment]
OK. Thanks for the explanation.
