### ISSUE TITLE
DPU Request: Extractor: SQL SELECT -> CSV

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#3]
Configurable extractor from relational DBs.
Has to support: login, various implementations (MS SQL, Oracle, Postgres, MySQL, H2, ...)

**Comment by tomas-knap** [comment]
SWC did DPU which is extracting data from MS SQL. Will add more info.

**Comment by tomas-knap** [comment]
@jakubklimek, there is e-relationalFromSql. Is that enough for the current needs? 

Note: the output of e-relationalFromSql is relational (SQL table), so we should tune this - we should provide relationalToCSV/RDF transformer (to convert SQL table to file/RDF), or add optional RDF output to e-relationFromSql.

**Comment by skrchnavy** [comment]
@tomas-knap please update title if we need another DPU, or close it if you see it as invalid requirement.

**Comment by tomas-knap** [comment]
There is e-relationalFromSql
