### ISSUE TITLE
Typo in t-tabularToRelational's configuration

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#303]
"Sepatator" in the configuration dialog of t-tabularToRelational should read "Separator".

Context: Latest develop commit (695e6a0e1580b7d8d4f896393210625541423a93).

**Comment by mbl-eea-sk** [comment]
Adjusted in https://github.com/UnifiedViews/Plugins/commit/a104333136aeb5d7a6eae23ec7750f8b4f069179
