### ISSUE TITLE
e-sparqlEndpoint: failed to replace DPU

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#313]
If I try to replace e-sparqlEndpoint DPU with its latest version (7a7a0920d1a6d9c3f7dcafd20387b5ba29b431eb), the following error is displayed:

```
Can't load instance from new bundle. Exception: org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.e-sparqlEndpoint_1.1.0.SNAPSHOT [54]" could not be resolved. Reason: Missing Constraint: Import-Package: com.fasterxml.jackson.core; version="[2.4.0,3.0.0)"
```

Is this an error of the DPU or is it caused by older version of UV in ODN 1.1.0?

**Comment by skrchnavy** [comment]
In pom there is this section:
```
        <!-- Dependencies required during runtime. -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.4.4</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.4.4</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.4.4</version>
            <scope>provided</scope>
        </dependency>
```
so it is expected that a bundle with jackson have to be installed at Core. Documentation in Readme.md of this DPU shall be updated to inform how to install bundle (similar to t-tabular).

**Comment by skodape** [comment]
@skrchnavy Any idea what should I do here?

I though that DPU should package all dependencies (if possible) so this situation does not happen - even if it's against the OSGI design, but that was not my decision.

@jindrichmynarz Quick solution - rebuild Core and copy new libraries, or manually copy those libraries from some Nexus. server into the dpu/lib directory.

**Comment by skrchnavy** [comment]
@skodape I agree with you, there must be reason to 'provide' some packages instead of bundling into DPU. I found the author of changes, fortunately it is commit in develop (b5bb1cf7c38b922950b15519e19b18df58955f8b) so released version is OK.

**Comment by tomas-knap** [comment]
Yes, manually copying the missing library (which appears in "target/lib" after building latest develop branch - module lib) to "target/lib" on the target instance and restarting frontend should solve the issue.

@skodape You are right that it is safer to put everything inside the DPU, unless it is really common package shared by certain amout of core DPUs.

 So I suggest to put libraries needed by e-sparqlEndpoint back to e-sparqlEndpoint. See https://github.com/UnifiedViews/Core/pull/489/files, which did the relevant change.

**Comment by skrchnavy** [comment]
Based on above comment we can close this issue as resolved (in develop), when Core released it will be included.

**Comment by tomas-knap** [comment]
Before closing, this adjustment should be then refined: UnifiedViews/Core#489 (https://github.com/UnifiedViews/Core/pull/489), so that it does not contain libraries which are directly bundled with e-sparqlEndpoint DPu.

**Comment by mkl-eea-sk** [comment]
Changes from https://github.com/UnifiedViews/Plugins/pull/296 has been reverted in develop, changes from https://github.com/UnifiedViews/Core/pull/489 has been reverted in Core/develop. There are new pull requests with original features (https://github.com/UnifiedViews/Plugins/pull/315 and https://github.com/UnifiedViews/Core/pull/516).

So this issue should be retested with latest develop and DPU should work as previously worked.

**Comment by jindrichmynarz** [comment]
Using 32e3f0777b7bc7f5ca849a06082ba04813fc7f75 the DPU can be replaced in UV in ODN 1.1.0. However, there are additional problems, for which I'll open separate issues.
