### ISSUE TITLE
e-sparqlEndpoint does not allow to switch paged execution off

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#318]
Using e-sparqlEndpoint from 32e3f0777b7bc7f5ca849a06082ba04813fc7f75, there's no option to switch paged execution off. This option was required by @tomas-knap in [his comment](https://github.com/UnifiedViews/Plugins/issues/241#issuecomment-126603512).

**Comment by mkl-eea-sk** [comment]
In develop, there is no paging support in develop branch. There is no paging, the DPU is the old one in develop
