### ISSUE TITLE
t-filesFilter: document what regular expression syntax can be used

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#320]
Currently it is not clear what regular expression syntax is supported by t-filesFilter "File name pattern" parameter. This should be described in the [DPU's documentation](https://github.com/UnifiedViews/Plugins/blob/master/t-filesFilter/doc/About.md).

**Comment by skrchnavy** [comment]
FilesFilter uses sparql and it's reqexp, see https://github.com/UnifiedViews/Plugins/blob/UV_Plugins_v2.1.2/t-filesFilter/src/main/java/eu/unifiedviews/plugins/transformer/filesfilter/FilesFilter.java#L50
need to be documented properly for users to understand what can be used.
