### ISSUE TITLE
t-filesFilter: string replacement bug

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#321]
t-filesFilter replaces the regular expression for the "File name pattern" parameter via [`String.replaceAll` method](http://docs.oracle.com/javase/7/docs/api/java/lang/String.html#replaceAll%28java.lang.String,%20java.lang.String%29) (see [the source](https://github.com/UnifiedViews/Plugins/blob/master/t-filesFilter/src/main/java/eu/unifiedviews/plugins/transformer/filesfilter/FilesFilter.java#L122)). If the regular expression contains special characters (such as `$`), then the replacement fails. The method's documentation warns about this problem:

> Note that backslashes (\) and dollar signs ($) in the replacement string may cause the results to be different than if it were being treated as a literal replacement string; see Matcher.replaceAll. Use Matcher.quoteReplacement(java.lang.String) to suppress the special meaning of these characters, if desired.

This should be fixed. Either the method of passing the regular expression into the SPARQL update should be changed, or the appropriate `Matcher.quoteReplacement` method should be used. When doing this, it would be great if the SPARQL updates were refactored as well. String munging when creating SPARQL queries in particularly brittle technique. Consider using [`Query.setBinding`](http://rdf4j.org/sesame/2.7/apidocs/org/openrdf/query/Operation.html#setBinding(java.lang.String, org.openrdf.model.Value)) method for the replacement.

**Comment by tomas-knap** [comment]
Relates with https://github.com/UnifiedViews/Plugins/issues/320
