### ISSUE TITLE
e-executeShellScript: Output directory should not be configurable

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#329]
Instead of allowing the users to specify "Output directory", the DPU should use its working space. Instead of being configured by the user, the output directory should be internally generated by the DPU.

(moved from original request: OpenDataNode/UVPlugin-executeShellScript#3)

**Comment by pgo-eea-sk** [comment]
Resolved by commit https://github.com/UnifiedViews/Plugins/commit/6b920bd45c0523e29c059577303121e3c12c750e
