### ISSUE TITLE
e-executeShellScript: Documentation improvement

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#331]
To document technical details of script (interface)

Into Readme.md TechnicalDetails section:
* The executed script must be prepared to expect 3 positional arguments: configuration, list of files, and output directory.
* List of files provided as the second argument is a plain text document with an absolute file path per line.
* all output files have to be placed into output directory

(Created based on issue in original location: OpenDataNode/UVPlugin-executeShellScript#1)

**Comment by pgo-eea-sk** [comment]
Resolved by commit https://github.com/UnifiedViews/Plugins/commit/6b920bd45c0523e29c059577303121e3c12c750e
