### ISSUE TITLE
e-sparqlEndpoint: Typo in Slovak localization

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#332]
In the Slovak locale for e-sparqlEndpoint the endpoint URL is written as "Enpoint URL". This should be corrected, or even better, made consistent with the label in l-filesToParliament, which is "URL koncového bodu".

**Comment by skrchnavy** [comment]
"URL koncového bodu" looks OK. @mbl-eea-sk please check also other SPARQL dpus if they are using SparqlEndpoint in slovak transklation and About_sk.md to use consistent wording

**Comment by mbl-eea-sk** [comment]
No other occurences found but some corrections to improve language purity have been done.
