### ISSUE TITLE
t-tabular: Documentation should be updated (doc/About)

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#335]
There is plenty of config options in t-tabular, but they are not documented. See: 

https://github.com/UnifiedViews/Plugins/blob/develop/t-tabular/doc/About.md
https://github.com/UnifiedViews/Plugins/blob/develop/t-tabular/doc/About_sk.md

doc/About*.md should be updated.

**Comment by tomas-knap** [comment]
Related to: https://github.com/UnifiedViews/Plugins/pull/364

**Comment by eea03** [comment]
Partly done in https://github.com/UnifiedViews/Plugins/commit/40ff10bf74b292d8d80b26f0721e871af5b7b49e
However documentation is not complete, missing input type specific parameters documentation as this general part was taken from T-RelationalToRdf DPU
