### ISSUE TITLE
e-silkLinker incorrect copy-paste Javadoc

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#336]
e-silkLinker's class `SilkLinker` contains incorrect Javadoc that was likely copy-pasted from a XSLT DPU.  See [here](https://github.com/UnifiedViews/Plugins/blob/master/e-silkLinker/src/main/java/eu/          unifiedviews/plugins/extractor/silklinker/SilkLinker.java#L42).

**Comment by tomas-knap** [comment]
Solved in https://github.com/UnifiedViews/Plugins/commit/90c7ea1a37ba824e9c9bddb9dcc502749e0086aa
