### ISSUE TITLE
e-silkLinker: empty output

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#348]
I have a Silk linkage rule that when run with e-silkLinker produces empty output, but when run with Silk on the command line, it produces some links. The linkage rule, the data sources, and the confidence level for the output are set to be the same in both cases.

Moreover, linking via e-silkLinker terminates much sooner than via Silk on the command line, which leads me to think if it actually terminates prematurely. I think about 2 possible causes:

1. e-silkLinker creates empty output files in advance and then the process in which Silk is run is not allowed to write to them (see #342).
2. e-silkLinker terminates before the process it spawned, killing the unfinished Silk process.

Context: I use the latest develop commit (33ceb3dbcf4bf0499e50783c5c0b41b6ecbc36ff).

**Comment by jindrichmynarz** [comment]
In fact, when I use an invalid Silk linkage rule that throws an error in the command line version, e-silkLinker stays silent and finishes with empty output.

**Comment by jindrichmynarz** [comment]
I also created a simpler linkage rule that basically links almost everything with almost everything (based on inequality) and while the command-line Silk produces output, the output of e-silkLinker remains empty.

**Comment by tomas-knap** [comment]
This is really strange. Option 1 is not probable. I am trying to call Silk directly (and not as an external process), but not being succesfull so far.

**Comment by jindrichmynarz** [comment]
I assume you were successful in using Silk as an external process in your work, so then the question is why is e-silkLinker unsuccessful: what is the difference between the version you have used and the committed version?

**Comment by tomas-knap** [comment]
There shouldn't be any difference. I was using Silk 2.5.3 as the Silk.jar. 

Anyway, trying to adjust the DPU so that it does not call Silk as external process, which solves couple of issues at once. So far was able to import to UV, but then there are some issues during runtime.

**Comment by jindrichmynarz** [comment]
I don't expect there is a difference in Silk. As a matter of fact I used the Silk JAR-file provided by you.

I suspect there might be a difference either in the DPU that you used and what you have committed here or in the version of UnifiedViews.

**Comment by tomas-knap** [comment]
Really strange. Can you please give me link to the linkage rule, for which e-silkLinker produces empty output, but command-line produces output? If the data the Silk is working on are not accessible via remote sparql endpoint, can you please provide dump for them?

**Comment by jindrichmynarz** [comment]
It seems I might have solved the issue. I was looking at the logs produced by the DPU and found this one: `Error: Unable to access jarfile /usr/local/bin/silk_2.5.3.jar`. I changed the owner of the JAR-file to `unifiedviews` and now it seems it is working.

Note that the above error is logged as warning (and therefore hidden in the other warnings), while it is clearly an error that should cause the pipeline to fail. It is also strange that this DPU requires the JAR-file to be owned by the `unifiedviews` user, because e-executeShellScript does not require that from the scripts it can execute.

**Comment by skrchnavy** [comment]
It is strange that DPU requires JAR file from /usr/local/bin, this jar shall be bundled into DPU.

**Comment by jindrichmynarz** [comment]
@tomas-knap: Can you update the DPU's documentation to say that the JAR-file needs to be owned by the `unifiedviews` user? Then we can close this issue.

**Comment by jindrichmynarz** [comment]
@tomas-knap: Also please change the WARN about unaccessible JAR-file to error.

**Comment by skrchnavy** [comment]
@jindrichmynarz I see this as error in DPU not wrong documentation, @tomas-knap to provide feedback

**Comment by tomas-knap** [comment]
To remove the need to specify link to Silk.jar, I created https://github.com/UnifiedViews/Plugins/issues/351

**Comment by tomas-knap** [comment]
Resolved in https://github.com/UnifiedViews/Plugins/pull/352
