### ISSUE TITLE
Empty output from e-filesDownload generates non-empty output if passed through t-filesToRdf and t-rdfToFiles

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#349]
If I use e-filesDownload to get a non-existent file (this raises warning), then pass it to t-filesToRdf and back to t-rdfToFiles it creates non-empty output, such as the following:

```

<http://unifiedviews.eu/resource/internal/dataunit/exec/732/dpu/948/du/0> <http://unifiedviews.eu/ontology/internal/data/read> <http://unifiedviews.eu/resource/internal/dataunit/exec/732/dpu/948/du/0> ;
	<http://unifiedviews.eu/ontology/internal/data/write> <http://unifiedviews.eu/resource/internal/dataunit/exec/732/dpu/948/du/0> ;
	<http://unifiedviews.eu/ontology/internal/data/counter> "0"^^<http://www.w3.org/2001/XMLSchema#int> .

<http://unifiedviews.eu/resource/internal/dataunit/exec/732/dpu/951/du/0> <http://unifiedviews.eu/ontology/internal/data/read> <http://unifiedviews.eu/resource/internal/dataunit/exec/732/dpu/948/du/0> , <http://unifiedviews.eu/resource/internal/dataunit/exec/732/dpu/951/du/0> ;
	<http://unifiedviews.eu/ontology/internal/data/write> <http://unifiedviews.eu/resource/internal/dataunit/exec/732/dpu/951/du/0> ;
	<http://unifiedviews.eu/ontology/internal/data/counter> "0"^^<http://www.w3.org/2001/XMLSchema#int> .

<http://unifiedviews.eu/resource/internal/dataunit/exec/732/dpu/951/du/1> <http://unifiedviews.eu/ontology/internal/data/read> <http://unifiedviews.eu/resource/internal/dataunit/exec/732/dpu/951/du/1> ;
	<http://unifiedviews.eu/ontology/internal/data/write> <http://unifiedviews.eu/resource/internal/dataunit/exec/732/dpu/951/du/1> ;
	<http://unifiedviews.eu/ontology/internal/data/counter> "0"^^<http://www.w3.org/2001/XMLSchema#int> .

<http://unifiedviews.eu/resource/internal/dataunit/exec/732/dpu/950/du/1/entry/1> <http://unifiedviews.eu/DataUnit/MetadataDataUnit/symbolicName> "still_not_there.ttl" ;
	<http://unifiedviews.eu/DataUnit/MetadataDataUnit/FilesDataUnit/fileURI> "file:/Users/mynarzjindrich/Dev/UnifiedViews/app/Core/backend/working/exec_732/storage/dpu_950/1/still_not_2252596351209794943" ;
	<http://unifiedviews.eu/VirtualPathHelper/virtualPath> "still_not_there.ttl" .
```

This looks a lot like metadata, so it seems that the DPUs mix up data with metadata.

Context: All used DPUs were compiled from the latest develop commit (33ceb3dbcf4bf0499e50783c5c0b41b6ecbc36ff).

**Comment by tomas-knap** [comment]
Increasing priority, this should NOT happen

**Comment by skrchnavy** [comment]
From description not clear which DPU is causing the troubles. I expect one of t-filesToRdf or t-rdfToFiles.

**Comment by jindrichmynarz** [comment]
That is the point. The issue arises (or can be replicated) only when the DPUs are used in combination. If I execute the pipeline in debug mode, then all intermediate inputs and outputs are empty, yet still the pipeline produces data.

**Comment by tomas-knap** [comment]
The problem was that there was "connection.export(writer, sourceUris);" in t-filesToRDF and if sourceUris were null (no data to be exported), whole repository was exported as this is the semantics of the export method (sourceUris are optional). 

@jindrichmynarz Please retest but it should no happen further.

**Comment by jindrichmynarz** [comment]
To be clear, as I understood from #353, the fix affects both t-filesToRdf and t-rdfToFiles, so I recompiled both of these DPUs.

When I run the test pipeline with the updated DPUs, the result is improved slightly but still not correct. Instead of producing a file with the above contents, the pipeline produces an empty file.

@tomas-knap, you should probably specify what is the expected behaviour here. For example:

- Throwing an exception in t-filesToRdf.
- Not producing any output in t-rdfToFiles.

**Comment by tomas-knap** [comment]
#353 addresses the fix for t-rdfToFiles (sorry for writting it wrong). For t-filesToRDF, it addresses nothing w.r.t  this issue. I will check and write how to finalize this issue.

**Comment by jindrichmynarz** [comment]
Not sure if I follow. If you look at the [files affected by the pull request](https://github.com/UnifiedViews/Plugins/pull/353/files), there are files from both t-filesToRdf and t-rdfToFiles.

**Comment by mbl-eea-sk** [comment]
Consider change in t-rdfToFiles only.
The update in t-filesToRdf is just a "cosmetic" improvement of String building.

**Comment by tomas-knap** [comment]
To be 100% correct, change in t-filesToRDF should not be in the same pull request.

**Comment by skrchnavy** [comment]
@mbl-eea-sk please also update CHANGELOG.md with info about changes in both DPUs.

**Comment by mbl-eea-sk** [comment]
OK, changelogs updated and changes in t-filesToRdf moved to pull request #354

**Comment by tomas-knap** [comment]
Adjusted, so that no file is produced if there is no input RDF data
