### ISSUE TITLE
t-filesToRdf: brittle format detection

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#350]
It seems that t-filesToRdf detects the format of the input RDF file by looking at its suffix. This is a brittle way of format detection.

For example, when I use e-filesDownload to retrieve an RDF file from local file system or the web and I leave the "File name" empty, t-filesToRdf fails with `org.openrdf.rio.UnsupportedRDFormatException: No parser factory available for RDF format null`. When I download `https://raw.githubusercontent.com/opendatacz/public-contracts-ontology/master/public-contracts.ttl`, I expect that e-filesDownload will name its output file `public-contracts.ttl` and the `*.ttl` suffix will be recognized by t-filesToRdf, however that is not the case (it seems that this was introduced when #274 was fixed).

I think a pragmatic solution to this issue is to allow to configure the format of the input in t-filesToRdf.

Context: I compiled t-filesToRdf from the latest develop commit (33ceb3dbcf4bf0499e50783c5c0b41b6ecbc36ff).

**Comment by tomas-knap** [comment]
Yes, it should be possible to specify the input format manually in any case (the extension may be wrong, missing etc.). By default, there should be AUTO.

**Comment by mbl-eea-sk** [comment]
Can someone advise me please, how does this DPU recognize the input file type?
As I have found out there are 6 RDF formats (RDFXML, N3, TRIG, TTL, TRIX, NT) and AUTO format. Now I have implmented combo box in Vaadin Dialog with choice from these formats but I am not sure how the main class handles there formats and what is the difference in further execution according to different format.
Thank you.

**Comment by jindrichmynarz** [comment]
Search through the Sesame documentation on that topic (for example, [here](http://rdf4j.org/doc/4/articles/rio-parser/format-detection.docbook?view)) and you will likely find helper methods to detect RDF serialization based on MIME type of checking the first few bytes of a file.

**Comment by tomas-knap** [comment]
As @jindrichmynarz said, thanks!

**Comment by tomas-knap** [comment]
See comments under #354
