### ISSUE TITLE
add binary releases

### ISSUE THREAD

**Issue by nvdk** [UnifiedViews/Plugins#355]
It would be convenient if a release would have a binary release of all dpu's (eg a zip containing the jar files). This would allow downloading dpu's without the need to build them.

**Comment by skrchnavy** [comment]
It is not necessary to build DPUs, they are in artifactory. Please check `debian/pom.xml` file in this repository where you can find hint how to write such maven project.

**Comment by nvdk** [comment]
Hey that would be a nice solution, however currently it seems http://maven.eea.sk/artifactory/public/eu/unifiedviews/plugins/uv-plugin-dpus/ does not have include the latest version of the parent pom (currently last version published is 1.6.0). 

I have a rather specific use case where I would install dpus via script on first run of a docker image and would like the easily retrieve them. Currently the following would work if the parent pom were available in the repository:

```
curl --output /dpus/pom.xml --silent https://raw.githubusercontent.com/UnifiedViews/Plugins/$PLUGINS_VERSION_TAG/debian/pom.xml 
mvn dependency:copy-dependencies -DoutputDirectory=/dpus	
```

Is it an oversight that the latest version of uv-plugin-dpus pom is not available or are you no longer planning to include it?

**Comment by skrchnavy** [comment]
Parent for UV plugins api v2.X shall be http://maven.eea.sk/artifactory/public/eu/unifiedviews/uv-pom-dpu/
It is necessary to do some changes also in the code to be compliant with API and helpers.

**Comment by nvdk** [comment]
Ok, in that case isn't the parent of the debian/pom.xml outdated? in fact does it even need a parent at all?
