### ISSUE TITLE
t-filesFilter: vague documentation

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Plugins#370]
The [documentation of t-filesFilter](https://github.com/UnifiedViews/Plugins/blob/develop/t-filesFilter/doc/About.md) should be make it clear that the filtering regular expression is applied to the *file path* and not the *file name*.

Relates to #369.

**Comment by jindrichmynarz** [comment]
It is still quite confusing. For example, the [linked documentation](https://grips.semantic-web.at/display/UDDOC/Basic+Concepts+for+DPU+developers) says that *"for Files data units, symbolic name is typically derived from virtualPath."* Since we're documenting t-filesFilter that operates on files, can we just say that it will filter over file paths to simplify things? Otherwise, if you say things like *"typically derived from virtualPath"*, then it is guessing in the dark.

**Comment by tomas-knap** [comment]
Yes, but I also updated the doc of t-filesFilter -https://github.com/UnifiedViews/Plugins/blob/develop/t-filesFilter/doc/About.md, where it is said that symbolicName is derived from virtualPath (not "typically" in this case). Should I further improve?

**Comment by jindrichmynarz** [comment]
OK, thanks. I think adding an example would help. For example, if I unzip an archive that expands to `/path/to/file`, what is the symbolic name? Is it `/path/to/file` or `{internal UV path}/path/to/file`?

**Comment by tomas-knap** [comment]
I adjusted documentation of the unzipper, to clarify better the way how symbolic name is constructed.
https://github.com/UnifiedViews/Plugins/blob/release/UV_Plugins_v2.2.1/t-unzipper/doc/About.md

**Comment by tomas-knap** [comment]
@jindrichmynarz Please reopen, if you need further clarification.
