### ISSUE TITLE
delete data not supported in uv-t-sparqlUpdate

### ISSUE THREAD

**Issue by bertvannuffelen** [UnifiedViews/Plugins#376]
Hi,

it seems that the following is 

delete  data {
coditemp:subject a coditemp:TempProperty.
 coditemp:document_category a coditemp:TempProperty.
 coditemp:document_type a coditemp:TempProperty.

} 

is not supported  (using LocalRDF)

Bert

**Comment by tomas-knap** [comment]
Works now, probably solved by using later version of sesame API
