### ISSUE TITLE
relationalFromSql or relationalToRdf does not produces result if the input is only one record

### ISSUE THREAD

**Issue by yyz1989** [UnifiedViews/Plugins#378]
Hi there,

I am not able to identify which DPU causes this error. The original input data is from a MSSQL database with a "TOP 1" constructor in the SQL query to get only one record. Then the output is fed to relationalToRdf for triplification and finally exported as a file. When we use "TOP 1" or a table with only one record, relationalToRdf produces no triple. When it is more than one, it produces number of records minus one triple sets.

Regards,
Yang

**Comment by skarampatakis** [comment]
I have somehow a same issue where relational DPU does not convert the last element of the table.
A temporal solution is to add another element on the end of the table.
Possibly different indexing?

**Comment by hanecak** [comment]
@skarampatakis can you please indicate version you are using (say output from `dpkg -l unified\*`)?

**Comment by skarampatakis** [comment]
UV 2.3
uv-t-relationalToRdf\uv-t-relationalToRdf-1.0.1.jar
uv-e-relationalFromSql\uv-e-relationalFromSql-2.1.3.jar

**Comment by hanecak** [comment]
Sorry for delay, we (me and @eea03) were not able to reproduce the problem nor find a culprit by code review.

If the problem still persists, can some of you (@skarampatakis or @yyz1989) please share input data and exported pipeline with us?

**Comment by tomas-knap** [comment]
Solved by: https://github.com/UnifiedViews/Plugins/issues/395
