### ISSUE TITLE
different serializations for string literals in t-rdfToFiles should provide consistent datatype statements

### ISSUE THREAD

**Issue by yyz1989** [UnifiedViews/Plugins#379]
Hi there,

I observed that the string literals in RDF/XML and TriX serializations are explicitly datatyped to xsd:string, but there are no datatypes associated in other serializations. I propose that we should have a consistent approach to datatype string literals. They should be either datatyped for all serializations, or not at all. Personally I hope they are not datatyped at all to be compatible with Virtuoso. According to RDF, a string literal without a language tag is implicitly datatyped to xsd:string, but Virtuoso treats them differently, for example 
```
ask {filter(datatype("a") = datatype("a"^^xsd:string))}
```
returns false, which is incorrect.

Regards,
Yang

**Comment by tomas-knap** [comment]
Yes, they should not be data typed, in case it is xsd:String. 

Note: The observed problem appears, e.g. in case of t-rdfToFiles, when resulting file is prepared. So it is probably an issue of Sesame. We can do a workaround only.
