### ISSUE TITLE
UnifiedViews Nexus repository down?

### ISSUE THREAD

**Issue by blankdots** [UnifiedViews/Plugins#417]
We are trying to build our own DPUs for UnifiedViews, however it seems that the Nexus repository we have been previously using is down:
```
       <repository>
            <id>repository.unifiedviews.eu</id>
            <name>repository.unifiedviews.eu-public</name>
            <url>http://repository.unifiedviews.eu/nexus/content/repositories/public/</url>
        </repository>
```
Is there a fallback repository we can make use of?

**Comment by tomas-knap** [comment]
Please try again, know about that, should be working again

**Comment by blankdots** [comment]
yeap fixed. thank you.
