### ISSUE TITLE
T-SPARQL -  bigger textarea for the query

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#45]
The textarea for the SPARQL query should be bigger. Otherwise it is very hard to write the query directly to such small textarea, one has to copy&paste from a different editor!

Tested for 1.3.1-snapshot

**Comment by skrchnavy** [comment]
@tomas-knap please update info about future of this DPU with respeect to new DPUs developed for specialize T-SparqlXXX (XXX = [Select|Construct|insert|Update]
Should we remove this DPU from distribution?

**Comment by tomas-knap** [comment]
I would suggest to close this issues. 

As part of https://github.com/UnifiedViews/Plugins/issues/92, t-sparql should be denoted as deprecated. Instead of t-sparql, t-sparqlConstruct and t-sparqlUpdate should be used.
