### ISSUE TITLE
E-HttpDownload: Multiple files download specified by incoming RDF data

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#46]
specification:
<pre><code>&lt;anything&gt; &lt;http://unifiedviews.eu/resource/downloadURL&gt; &lt;url to download from&gt; .
&lt;something else&gt; &lt;http://unifiedviews.eu/resource/downloadURL&gt; &lt;url to download from&gt; .
...
</code></pre>

**Comment by tomas-knap** [comment]
@jakubklimek Is this still relevant?

**Comment by jakubklimek** [comment]
It is not. We have a different DPU with a proper RDF configuration for multiple files download

**Comment by mkl-eea-sk** [comment]
move on to e-filesDownload

**Comment by mkl-eea-sk** [comment]
where is a better dpu located? wouldnt be nice to have it merged with e-filesDownload?

**Comment by tomas-knap** [comment]
See #93

**Comment by skrchnavy** [comment]
@tomas-knap - I understood that we can close this issue as 'won't fix' or duplicate to #93

**Comment by tomas-knap** [comment]
Use e-filesDownload
