### ISSUE TITLE
T-FilesRenamer slow

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#48]
![image](https://cloud.githubusercontent.com/assets/718827/4185853/8e95e884-375b-11e4-9bb8-7d3c0cc68787.png)
Renamed 8000 files in 35 minutes... that seems slow.

**Comment by skrchnavy** [comment]
This could be simulated easy way:
* create zip file containing 1000 different files (names are different, content could be empty)
* create pipeline consisting of: extractor from local fs or http -> unzipper -> renamer -> zipper -> loader to local fs.
* run the pipeline and measure the performance.

**Comment by tomas-knap** [comment]
relates to #49

**Comment by skodape** [comment]
I reassgin to my self as I try to solve this problem during DPU migration phase.

**Comment by tomas-knap** [comment]
Solved by introducing t-filesRenamer 2.0.1
