### ISSUE TITLE
T-FilesRenamer is not a renamer yet

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#49]
is not a renamer. It only changes extension to .ttl

**Comment by tomas-knap** [comment]
@eea02, you were assigned by @skrchnavy, what is the latest status?

**Comment by skodape** [comment]
Can this be reassigned to me? As I'm updating the DPU I can also try to solve this as well.

**Comment by skrchnavy** [comment]
@skodape @tomas-knap - please check DPU in released version 1.5.5. There is commit 0ea1f0175a3d6c65f44fbb35661a408ab7c811c6 where this was implemented.
If it is OK, we shall close this.

**Comment by tomas-knap** [comment]
Superseded by t-filesRenamer 2.0.1, see https://github.com/UnifiedViews/Plugins/tree/develop/t-filesRenamer
