### ISSUE TITLE
E-HttpDownload file not found exception cycles forever

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#57]
![image](https://cloud.githubusercontent.com/assets/718827/4555447/c564846e-4ebd-11e4-9430-df743450446f.png)

I forgot to upload a file to http://opendata.cz/kuba/mfcr/ciselniky/polvyk500fix.xml, so E-HttpDownload said correctly "file not found". Then however, it tries again and again to download, so I uploaded the correct file, but that did not help - still says file not found. Probably because it tries to download a different file: http://opendata.cz/kuba/mfcr/ciselniky/polvyk500fix.xml/-1 for some reason.

**Comment by tomas-knap** [comment]
#93 is a blocker. DO not solve this issue before #93 is solved

**Comment by tomas-knap** [comment]
Use e-filesDownload, this DPU is obsolete.
