### ISSUE TITLE
T-RDFtoFiles quads with custom graph URI support

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#59]
T-RDFtoFiles has to support RDF quad file formats: N-Quads, TriG and needs to be able to correctly set the output Graph URI.

**Comment by tomas-knap** [comment]
Currently, it supports to set up one graph to which all data is stored. Missing: Possibility to define more than one graphs

**Comment by mkl-eea-sk** [comment]
use VirtualGraphHelper for this

**Comment by tomas-knap** [comment]
More than one output graph not needed, closing
