### ISSUE TITLE
E-HttpDownload - configuration dialog improvements

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#61]
Make configuration dialog look better, formatting, big textarea not on right side. Clear instructions for user how to configure.
Add option to specify virtualPath for each file.
Support virtualPath metadata - default - the filename from http headers received.

**Comment by tomas-knap** [comment]
DO not solve this before #91 is solved - there is one aligned httpDownloader

**Comment by skrchnavy** [comment]
@skodape was this relevant for #91?

**Comment by skrchnavy** [comment]
@tomas-knap is this relevant also for filedDownload DPU? If not I propose to close as this is discontinued DPU.

**Comment by skrchnavy** [comment]
@tomas-knap please comment, close if not relevant any more.

**Comment by mkl-eea-sk** [comment]
obsolete dpu
