### ISSUE TITLE
There should be a possibility to generate incremental updates by loaders

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#63]
Data publisher must have a possibility to publish incremental updates, thus, each next run of pipeline is  generating new data, not overwriting the existing. 

So it must be possible to specify that loader/rdf2file should always generate a file according to pattern  {name}-{date}, where name is fixed and data is always added as current date. 

Tato funkcionalita byla na konci studentskeho proj v puvodnim loaderu, viz:
https://grips.semantic-web.at/display/UNVI/DPU+-+RDF+File+Loader
Jenze ten se zahodil, bo se neloaduje do filu primo z RDF data unit, ale pres rdf2file dpu.

**Comment by skrchnavy** [comment]
@tomas-knap - is in progress in files renamer. @eea02 shall comment.

**Comment by eea02** [comment]
Reworked FilesRenammer DPU is able to to this. Now you can rename files according to a mask. It has a very similar function as TotalCommander's rename utility.

**Comment by tomas-knap** [comment]
Test FilesRenamer DPU than close

**Comment by tomas-knap** [comment]
TODO: Check whether this feature is needed? It was adjusted in t-filesRenamer 1.X, which was superseeded by t-filesRenamer 2.X, which does not have this feature

**Comment by tomas-knap** [comment]
Not needed, closing
