### ISSUE TITLE
Adjust configuration dialog for DPUs in UV/Plugins repo

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#64]
Please start by summarizing guidelines for DPU developers and put these guidelines to https://grips.semantic-web.at/display/UDDOC/Creation+of+Plugins (as a subpage)

Then adjust the DPU which are in 1.4.0 release according to guidelines

Some hints (in Czech): 

Aby to nebylo ve stavu, ze si otevru dialog DPU a polovinu text boxes vubec nevidim, text boxes zacinaji v pulce obrazovky atd.  
 
Je tam jen jeden urgentni problem a to, ze autori nekterych DPUs delaji moc kratke input fields a hlavne to layoutuji tak, ze nektere fields jsou schovane a chybi scrollbar, takze pak field neni videt.

**Comment by skrchnavy** [comment]
closed; if any new comment to particular DPU, new issue per DPU shall be raised
