### ISSUE TITLE
T-SPARQL: remove checkbox that cannot be unchecked or allow checking

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#71]
![image](https://cloud.githubusercontent.com/assets/718827/5044099/f7966474-6bec-11e4-938c-b66cff5f2d70.png)

1) I did not notice that we agreed on removing this functionality, but OK, may be unnecessary
2) But if it really is removed, why is the checkbox still there? Does not make any sense. Especially when someone changed the label to "cannot be changed".

**Comment by skrchnavy** [comment]
@tomas-knap see also [my comment](https://github.com/UnifiedViews/Plugins/issues/45#issuecomment-70854970) in #45 to update status of this this issue.

**Comment by tomas-knap** [comment]
Wont't fix as t-sparql will be deprecated
