### ISSUE TITLE
T-FilesFilter : New user will hardly understand its user interface

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Plugins#72]
1) Description "Filter by : symbolic name for .*" is useless, no user knows what "symbolic name" means. More usefull description would be "Filters files on the input using the specified name pattern."

2) Used filter: There are two options (symbolic name, virtual path) - I do not understand any of them. There should be only one filter - name of the file. No options should be there.

3) Custom predicate : It is not clear what it is. It should be "File name pattern" and it should accept a path to the file specified as a fixed string or as a regular exprssion. A file name is a special case of a path.

4) Checkbox User  regular expression : I suppose it belongs to the input text field above so it should also be better associated visually. Put it higher or above the text field. Remove ':'

![image](https://cloud.githubusercontent.com/assets/4235208/5046014/5bf23cfa-6c05-11e4-93bd-c205cff7fb75.png)

**Comment by skrchnavy** [comment]
Based on analysis of commit da18b2db9e8cfc5adf2213e9f1f766c01a6d8015 it is not available in any branch. Issue moved to milestone 2.2.0

**Comment by mkl-eea-sk** [comment]
Commit https://github.com/UnifiedViews/Plugins/commit/da18b2db9e8cfc5adf2213e9f1f766c01a6d8015 is not relevant. @mbl-eea-sk  provide valid commit please.

**Comment by mbl-eea-sk** [comment]
https://github.com/UnifiedViews/Plugins/commit/5d47ecf9de58a6884d1c3b3322edec4c377b17eb#diff-e5e376201f6e648199b44dfa8618e498
This is already solved.

**Comment by skrchnavy** [comment]
based on above info (commit 5d47ecf9de58a6884d1c3b3322edec4c377b17eb) this issue is solved from v2.0.0 of Plugins. If OK, then  we can close this as resolved.
