### ISSUE TITLE
T-FilesFilter : Skipping field customPredicate warning

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Plugins#73]
I run the pipeline "[EH_1] ATC published by SIDC" and got a warning from T-FilesFilter:

![image](https://cloud.githubusercontent.com/assets/4235208/5046163/2060dbcc-6c07-11e4-9c7f-fcbf0689f2c3.png)

I do not understand this warning. The value of the filter is specified correctly and the pipeline filtered the file I wanted. Therefore, there was no problem. Anyway, I got the warning. This is confusing. The warning should be removed.

**Comment by pedrinazzi** [comment]
is it possible share the complete pipeline to repeat the test properly?

**Comment by skrchnavy** [comment]
Is this message generated from DPU or is it from an Exception caught in DPU?
