### ISSUE TITLE
UK-T-Tabular : Warnings not clear

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Plugins#74]
When I run "" I got a strange warnings "useTableSubject : Not equals!" and "generateTableClass : Not equals!". I do not know what these warnings mean, what I made wrong in the configuration? The warnings should be more detailed so that the users recognizes what he should improve in the configuration.

![image](https://cloud.githubusercontent.com/assets/4235208/5046839/5489a2fa-6c0f-11e4-9dd3-9da86e3505bb.png)

**Comment by pedrinazzi** [comment]
is it possible share the complete pipeline to repeat the test properly?

**Comment by tomas-knap** [comment]
Do not solve this until #91 is solved, as for now tabular is not available in mff-uk/DPUs. #91 is blocker

**Comment by skrchnavy** [comment]
Subject of issue shall be changed to reflect this repository

**Comment by skodape** [comment]
Martin is this still actual? As this is the problem with the helpers not with the Tabular. I agree that the massage should be better.
This might already get fixed as I done some changes since this issue was reported.

**Comment by tomas-knap** [comment]
Invalid as the helpers changed significantly. If we encounter such issue with new helpers, please reopen
