### ISSUE TITLE
E-RdfFromSparqlEndpoint : Make textbox for sparql query resizable

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Plugins#75]
The textbox for specifying sparql query in the user interface of E-RdfFromSparqlEndpoint is small and cannot be resized by the user. Make it resizeable.

**Comment by pedrinazzi** [comment]
First solution could  be use ExpandedTextArea Vaadin Component. ( we need to produce the jar with the complete dependencies. Does UW work properly with such class?), Second one use fullsize method for  both textarea and layout objects, and resize the window using the window's right corner (it already works) or decide to use the scrool bar. Which solution do you prefer?
