### ISSUE TITLE
T-XSLT bad memory management

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#76]
When processing larger number of files (200 000) T-XSLT takes more and more memory and never frees it. It is not possible for t-xslt to take 12GB of RAM to process a 30KB file...

See https://cuni-test1.comsode.eea.sk/unifiedviews/#!ExecutionList/page=1&pipeline.name=ares&exec=2491 and filter T-XSLT log message by "Memory used"

**Comment by tomas-knap** [comment]
@jakubklimek Is this still relevant?

**Comment by jakubklimek** [comment]
This is fixed by @skodape

**Comment by mkl-eea-sk** [comment]
I am curious about the fix, where it is, i would like to merge enhancements to plugins repository.

**Comment by skrchnavy** [comment]
@skodape please provide a commit number wher it was fixed to close this issue.

**Comment by skodape** [comment]
I think is here https://github.com/UnifiedViews/Plugins/commit/0fcdab8d5db4becf1906cf029eec2ec75baddc6d
those lines with .close (136) and 137

CUNI XSLT has been committed as it's so there is no repair commit.

**Comment by mkl-eea-sk** [comment]
close should be definitely in finally block. should be updated.

**Comment by skodape** [comment]
I see why you consider this to be such a problem as it really is and made XSLT unusable on non-server computers. 

But original DPU XLST may be replaced so this is no longer relevant for me right now, so re-assigned to @skrchnavy to decide what to do next.

**Comment by tomas-knap** [comment]
Summary: Do not further discuss before the DPUs for XSLT are aligned. Then we can decided if the problem is still in the aligned XSLT

**Comment by mkl-eea-sk** [comment]
no hlavne by som chcel vidiet to druhe xslt. mozete ho odtajnit?

**Comment by skrchnavy** [comment]
Ano, ja by som tioez rad vedel kde je ten update

**Comment by skodape** [comment]
Moje tajné DPU .. :) ne není tajné a není moje, sedí na cuni repository tak jako helpery.

https://github.com/mff-uk/DPUs/tree/feature/2.0.0/dpu/t-xslt

Je tam pokus o více vláknovost, jenž není ještě otestovaná a tedy ani příliš rozpracovaná. Ale je možné se podívat na starší verze.

**Comment by mkl-eea-sk** [comment]
viac vlakonovost sprav prosim podla
https://github.com/UnifiedViews/Plugins/blob/develop/l-filesToVirtuoso/src/main/java/eu/unifiedviews/plugins/loader/filestovirtuoso/VirtuosoLoader.java
pouzitie multi threadovej queue na joby je samozrejme dobre.
aj ked by malo v tomto pripade ist skor o pull mechanizmus, pustis 
workery cez executor (thread pool) a staci jedna
synchronized metoda getNextJob() ktora vracia z iteratora nad subormi.
Worker sa zrusi ak mu pride null (minuly sa joby).

je tam aj priklad ako reportovat postup (pozri ci bezia, printni stav). 
ty si mozes spravit atomicinteger ktory budu inkrementovat ak spravia 
subor a zobrazis i/total.

rozhodne ten plain-thread system zahod.
thread.start aj join pouzivame az ked sme zufali.

**Comment by mkl-eea-sk** [comment]
ono inac a toto je presne ten MAP problem, ktory som chcel ze spravme 
helper pre DPU kde bude
1. napis execute (jeden file)
2. povedz kolko workerov
3. pusti
a cele rozdelenie a hranie s threadmi spravi helper a dpu developer 
napise len tu metodu execute(jeden file)

co je presne metoda "map" v mapreduce. pripadne rovno ako mapreduce to 
moze byt, ved to je uz jedno.
vsetky 1:1 transformacie by sa tak dali spravit, aj t-sparql kde query 
je per input symbolic name(graph), to iste relational data unit, xslt, 
kopirovanie suborov, stahovanie suborov, csv>relational, csv>rdf. vsetko 
co je 1:1.

**Comment by skodape** [comment]
Beru to tak, že to myslíš v dobrém, nicméně i tak nevím jestli se to stane - pokud to bude pracovat a nebude padat.

**Comment by mkl-eea-sk** [comment]
no v najlepsom to myslim, tak aby sme mali highquality code.
no ked si pozries ako je ten virtuoso , tak to nie je tkae strasne 
prepisat. ale ok, ty si sef svojho kodu.

**Comment by skodape** [comment]
No to by asi chtěli všichni i když se můžeme lišit v prioritách. Hold někdo hřeší na kódu, někdo na designu, atd .. myslím že klíčové slovo "čas" bohužel asi není třeba nikomu kdo umí česky/slovensky tady vysvětlovat.

Zkusím pracovat více a snad na to vyjde čas .. zase je pozitivní, že na nástřel před odchodem z práce je na tom i něco pozitivního.

**Comment by tomas-knap** [comment]
Current situation: XSLT still takes more memory than when it is run from a command-line. @jakubklimek Please report whether it is still an issue for the existing datasets we need to process.

**Comment by mkl-eea-sk** [comment]
this dpu is obsolete

**Comment by tomas-knap** [comment]
Yes, please retest t-xslt v2.X, if the problem is still there, please reopen
