### ISSUE TITLE
T-Sparql - when saving t-sparql, new 2 tabs are added to the list of tabs

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugins#78]
Everytime t-sparql is saved, new 2 tabs with default query is created!

To reproduce: Put t-sparql on canvas, with one query. Save. Open. there are +2 tabs. Save. Open. ...

Possible cause: 
https://github.com/UnifiedViews/Plugins/commit/4294ed45a6acd224f97ce989604762cfc90d6208

Removing the line added in the commit above fixes this issue. Another mean should be think of to ensure #44 T-SPARQL - no tab for the query by default.

**Comment by jindrichmynarz** [comment]
I've also encountered this issue. Does the multiplication of tabs with queries mean that all these queries are run?

**Comment by skrchnavy** [comment]
Isn't is similar to #125 ? Wouldn't be a solution as is fixed in 3ff4b8a3a2691dbc459a6e1387d82da46a9b8010 ?

**Comment by jindrichmynarz** [comment]
Moreover, it seems that queries in closed tabs are still saved and executed. This affects all pipelines that do data transformation via t-sparql, therefore I suggest changing priority to urgent. As @skrchnavy suggested, the fix might be simple.

**Comment by tomas-knap** [comment]
Solution is proposed in the description above, yes, solution is simple (one line).
