### ISSUE TITLE
e-httpDownload parameters: readtime and timeout should be configurable

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Plugins#79]

**Comment by tomas-knap** [comment]
#93 is a blocker of this issue

**Comment by mkl-eea-sk** [comment]
e-httpDowndload should be obsolete and replaced by e-filesDownload...

**Comment by skrchnavy** [comment]
e-httpDowndload will be merged (as defined in #93) and kept in repo.
Readme file will be updated with information that this DPU is not supported and e-filesDownload shall be used.

**Comment by jindrichmynarz** [comment]
I believe this issue was resolved by #229. Can we close it?

**Comment by skrchnavy** [comment]
@mkl-eea-sk / @skodape  please confirm that this was implemented under #229

**Comment by mkl-eea-sk** [comment]
resolved in #229
