### ISSUE TITLE
XSLT2 use XSL template from Files data unit on input - should enable XSL splitted into more than one file

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Plugins#81]
Put Files Data Unit input to XSLT2, it will contain XSL templates, linked by XSL syntax. Put these templates to transformer instead of one in config. 
This will enable template to be splitted into multiple files.
Adjust config dialog to contain only non-template options (basically, only skipOnError option will remain).
This feature is supported by File Uploader.

**Comment by tomas-knap** [comment]
Jindrich Mynarz has some dataset (SNK?) which will require XSLT splitted to more files, needs confirmation

**Comment by jindrichmynarz** [comment]
No, this is not a requirement. Every XSL transformation can be concatenated into a single file. It would be just more convenient to be able to use multiple XSL files (e.g., `<xsl:import>` a library of functions to allow better code reuse).
