### ISSUE TITLE
T-Metadata used to have "statistics" input which is now missing

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#84]
This was used for incremental datasets and datasets that cannot pass all data to T-Metadata (ruian) - in this case, T-Metadata was paired with a special extractor that ran the queries on the remote endpoint, passed them to T-Metadata, which then only added metadata from its form.

See https://github.com/mff-uk/DPUs/blob/release/1.2.2/dpu-domain-specific/metadata/src/main/java/cz/opendata/linked/metadata/form/Extractor.java#L44

**Comment by tomas-knap** [comment]
Ask @jakubklimek for details before solving

**Comment by tomas-knap** [comment]
T-Metadata is deprecated
