### ISSUE TITLE
T-XSLT: Literal label cannot be nulljava.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Plugins#86]
![image](https://cloud.githubusercontent.com/assets/718827/5280087/d5a41366-7aec-11e4-908a-73877a076f86.png)

**Comment by tomas-knap** [comment]
@jakubklimek Is this still relevant?

**Comment by tomas-knap** [comment]
@jakubklimek Please add steps to reproduce, how was the t-xslt configured?

**Comment by tomas-knap** [comment]
Cannot be reproduced
