### ISSUE TITLE
T-Metadata - wrong default list of availale licences

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Plugins#89]
In the T-Metadata, In the list of available licences there is by default

http://opendatacommons.org/licenses/pddl/1-0/
http://creativecommons.org/licenses/by/3.0/lu/

The second one is nonsense - it is a Luxembourg version of CC 3.0. There should be CC4.0

Therefore, there should be by default

http://opendatacommons.org/licenses/pddl/1-0/
http://creativecommons.org/licenses/by/4.0/

**Comment by skrchnavy** [comment]
@tomas-knap : Is T-Metadata DPU to be hosted in Plugins? Isn't this very specific DPU?

**Comment by tomas-knap** [comment]
T-Metadata is generic DPU needed when UV is used without CKAN. It should be in the Plugins repo.
