### ISSUE TITLE
UK-T-Tabular

### ISSUE THREAD

**Issue by martinnec** [UnifiedViews/Plugins#90]
UK-T-Tabular cannot process XLSX files. For example, this one:

http://www.strukturalni-fondy.cz/getmedia/b3b6bd76-d611-4e9e-bd2c-399edf29d690/2015_01-Seznam-prijemcu-(List-of-Beneficiaries)-01_2015.xlsx

I converted it to XLS and it works so there is really a problem with XLSX files.

**Comment by skrchnavy** [comment]
@martinnec please raise this issue in the repository for UK-T-Tabular, this is not relevant place.
Then please close this issue.

**Comment by martinnec** [comment]
And what is the relevant place?

**Comment by skrchnavy** [comment]
I am not sure ( @skodape to confirm) but I suspect this DPU is in question: https://github.com/mff-uk/DPUs/tree/master/dpu/t-tabular

**Comment by tomas-knap** [comment]
Since uk-tabular will replace existing tabular, it is relevant issue. Blocker is #91

**Comment by skodape** [comment]
This has already been fixed with UK-Tabular see. https://github.com/mff-uk/DPUs/issues/99

**Comment by skrchnavy** [comment]
This will be closed when Tabular DPU merged into this repo.
