### ISSUE TITLE
Align DPU: t-Tabular

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#91]
there are 2 versions of T-Tabular
* UnifiedViews/Plugins repo (this repo)
* mff-uk/DPUs repository

One version is enough so all good features from mff-uk/DPUs repository shall be migrated here.

Also DPU could be renamed to T-TabularToRDF or similar way.

**Comment by jakubklimek** [comment]
The one in UnifiedViews/Plugins was deprecated a long time ago and is no longer in use. Can be deleted. The only one in use is the one in mff-uk/DPUs repository.

**Comment by skrchnavy** [comment]
I agree with 100% replacement of Plugins tabular with mff-uk tabular. Just consider renaming of DPU because of tabularDataUnit.

**Comment by jakubklimek** [comment]
Shouldn't tabularDataUnit be rather called relationalDataUnit? We have relational databases, not tabular databases.

**Comment by skrchnavy** [comment]
Yes, I also came to similar conclusion, my idea was sqlDataUnit. Anyway still renaming is in question, because there will be t-tabularToSql or similar.

**Comment by tomas-knap** [comment]
Note: In order to migrate tabular in mff-uk/DPUs, we have to solve the alignment of helpers before, because mff-uk/DPUs use CUNI helpers.

**Comment by skrchnavy** [comment]
Documentation for t-Tabular shall be updated as part of this task, including version history. (https://github.com/UnifiedViews/Plugins/blob/master/t-tabular/README.md)

**Comment by tomas-knap** [comment]
Version history will be further maintained, be we will not recreate history back to past.
