### ISSUE TITLE
Align DPU: e-filesDownload

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#93]
there are 2 versions of httpDownload extractor
* e-httpDownload in UnifiedViews/Plugins
* e-httpDownload in mff-uk/DPUs

There is also e-filesDownload  in UnifiedViews/Plugins

One version is enough so all good features from mff-uk/DPUs repository shall be migrated here.

**Comment by tomas-knap** [comment]
Note: In order to migrate DPUs from mff-uk/DPUs, we have to solve the alignment of helpers before, because mff-uk/DPUs use CUNI helpers.

**Comment by tomas-knap** [comment]
Note: When E-FilesDownload (https://github.com/UnifiedViews/Plugins/issues/95) replaces e-httpDownload in UnifiedViews/Plugins. 

Either E-FilesDownload has to be merged with e-httpDownload in mff-uk/DPUs (which means to add support for RDF configuration provided by the input to E-FilesDownload), or there will be two DPUs (which is also a possibility).

**Comment by skrchnavy** [comment]
Due to backward compatibility I suggest to keep also e-HttpDownload, just we shall update documentation with reference to more universal downloader and setup this DPU as 'unsupported' (new features are not planed)

**Comment by skrchnavy** [comment]
This tasks is also related to E-FilesDownload to implement optional input data unit as requested in https://github.com/UnifiedViews/Plugins/commit/08847cc73170d3177d5cc911bf84cfc2ba0e56c5#commitcomment-9559548:

@tomas-knap : One remark. Be careful when this DPU will be merged as part of COMSODE with mff-uk/DPUs/e-httpDownloader, see #93. Either this DPU must be extended to support also RDF configuration received as the input or there will be two DPUs. RDF configuration is used on some pipelines to generate list of URIs to be downloaded

@skrchnavy : rdf data unit as optional input - accepted. inspiration in https://github.com/mff-uk/DPUs/blob/master/dpu/e-httpDownload/src/main/java/cz/cuni/mff/xrg/uv/extractor/httpdownload/HttpDownload.java (to check if not newer version in other branch)

@tomas-knap : To accomplish 4), CUNI helpers needed. SO I would suggest to solve comments 1. - 3. Point 4 will be solved as part of #93

**Comment by tomas-knap** [comment]
Blocked by #125 #126

**Comment by skrchnavy** [comment]
#125 fixed->closed
#126 fixed->closed
