### ISSUE TITLE
new DPU: FilesUpload Loader

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#94]
Loader DPU that supports various protocols for loading data into local/remote file system.
Uses: http://commons.apache.org/proper/commons-vfs/

**Comment by skrchnavy** [comment]
implemented in 177f9566ed465ee84c61c0f91dafaa156249c173

**Comment by skrchnavy** [comment]
@eea01  to implement hat is requested in https://github.com/UnifiedViews/Plugins/commit/177f9566ed465ee84c61c0f91dafaa156249c173#commitcomment-9560827

**Comment by eea01** [comment]
Finished in commit 39f1907226a7e9f931b646b96fb58188c492b2ef.
