### ISSUE TITLE
new DPU: FilesDownload Extractor

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugins#95]
Extractore DPU that supports various protocols for extract (download) data from local/remote file system.
Uses: http://commons.apache.org/proper/commons-vfs/

**Comment by skrchnavy** [comment]
implemented in 08847cc73170d3177d5cc911bf84cfc2ba0e56c5

**Comment by skrchnavy** [comment]
@eea01  - comments to commit  08847cc73170d3177d5cc911bf84cfc2ba0e56c5 from @tomas-knap  to be addressed

**Comment by skrchnavy** [comment]
@eea01 to implement as defined in https://github.com/UnifiedViews/Plugins/commit/08847cc73170d3177d5cc911bf84cfc2ba0e56c5#commitcomment-9558868

**Comment by eea01** [comment]
Finished in commit 64a7e58942a3bb00a5c004ae1cf9e6c9b1e0f7ca.

**Comment by eea01** [comment]
I am new to this workflow, does the status "approved by tknap" mean automatically to merge the feature branch into develop and remove the feature branch?

**Comment by tomas-knap** [comment]
yes

**Comment by eea01** [comment]
Done.
